### ISSUE TITLE
[Feature Request] Cannot customize handler

### ISSUE THREAD

**Issue by paulsouche** [DataDog/serverless-plugin-datadog#113]
## Expected Behavior

Be able to put specific `datadog-lambda-js` in a layer. 

## Actual Behavior

According to [this line](https://github.com/DataDog/serverless-plugin-datadog/blob/master/src/wrapper.ts#L52), the handler can be `/opt/nodejs/node_modules/datadog-lambda-js/handler.handler` with `addLayers: true` and `node_modules/datadog-lambda-js/dist/handler.handler` with `addLayers: false`.

What could be great is to have handler `/opt/nodejs/node_modules/datadog-lambda-js/dist/handler.handler` with `addLayers: false`

##  Why ?

Long story short... We have an issue with `@aws-crypto/client-node` using `readable-stream` under the hood and throwing module resolution errors in an other layer. This occurs only if `datadog-lambda-js` wraps our handler. So the idea is to have only one layer with everything in it because we can't get it work even with changing layers order...

## How ?

The `addLayers` configuration could be improved by a `layer` setting that could be a string or a boolean. e.g.

`layers: true` => `Handler: /opt/nodejs/node_modules/datadog-lambda-js/handler.handler` + add Layer (default) 
`layers: false` => `Handler: /node_modules/datadog-lambda-js/handler.handler` + no Layer
To keep the old behavior
`layers: my/path/to/datadog-lambda-js` => `Handler: my/path/to/datadog-lambda-js` + no Layer
For this feature

## Specifications

  - Serverless Framework version: 2.23.0
  - Datadog Serverless Plugin version: 2.16.2
  - Lambda function runtime (Python 3.7, Node 10, etc.): node14
  
## Stacktrace
  
NA

Thanks anyway for the great job

EDIT

BTW I can do a PR on this if this feature is OK for you

EDIT 2

The `readable stream` issue occurs because it is in `v1.1.14` inside the datadog layer but `@aws-crypto/client-node@2.1.0` requires it at version `^3.6.0` in `@aws-crypto/decrypt-node@2.1.0`

EDIT 3
The same behaviour could be done for the datadog SAM macro

**Comment by tianchu** [comment]
Thanks for submitting this feature request, and thanks everyone else putting a 👍 here for letting us know this feature is useful. We are reviewing https://github.com/DataDog/serverless-plugin-datadog/pull/149 and while waiting, I wonder (untested) if a workaround could be adding a symlink to at `node_modules/datadog-lambda-js/dist/handler.handler` in your project's deployment package that points to `/opt/nodejs/node_modules/datadog-lambda-js/handler.handler`?

**Comment by paulsouche** [comment]
Hello !

For those having this issue, we fixed it by putting our layer in a "sub folder"

Before we had
```yaml
AppLayer:
  Type: AWS::Serverless::LayerVersion
  Properties:
    LayerName: !Sub '${AWS::StackName}'
    ContentUri: .layer
    CompatibleRuntimes:
        - nodejs14.x
```
And in `.layer`
```
.
└── nodejs
          └── node_modules
```

After we have
```
.
└── nodejs
          └── node14 
                    └── node_modules
```
`AWS` does not mix the two layers anymore this way

Thanks anyway for the great job
