### ISSUE TITLE
Newer versions of the plugin are causing "Function code combined with layers exceeds the maximum allowed size" errors

### ISSUE THREAD

**Issue by noahw3** [DataDog/serverless-plugin-datadog#116]
## Expected Behavior

Serverless is able to upload reasonably-sized function code and the datadog layer without erroring.

## Actual Behavior

I'm receiving `An error occurred: PostBidLambdaFunction - Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 264579366 bytes. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 8d181d55-7773-45fd-9713-c8f36f435a28; Proxy: null).` errors when trying to deploy.

Zipped, the function code size is 15.54 MB. Unzipped, the function code is 85 MB. So it shouldn't be an issue of just barely pushing past the limit.

Using serverless-plugin-datadog@2.12.0 works as expected. Trying to upgrade to latest (2.17.0) caused this to manifest.

## Steps to Reproduce the Problem

  1. Create a function with >85MB unzipped function code size
  1. Add serverless-plugin-datadog@2.17.0
  1. Attempt to deploy

## Specifications

  - Serverless Framework version: 2.28.7
  - Datadog Serverless Plugin version: 2.17.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 12

One potentially odd tidbit: My first assumption was that the fault was on my function code for being too large. Sure enough, unzipped it was over 260MB. I cut out some duplicated versions and brought it down to the 85MB described above. However, it didn't make a difference. In addition, rolling back to 2.12 with that large function package ALSO was successful. So the common factor seems to be the size of this layer.

The error message with the 260MB package was interestingly only slightly different in the "actual size" that it spit out. `An error occurred: PostBidLambdaFunction - Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 264574862 bytes. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: d0b9b944-6f6a-45e9-bb9e-1ca083c68c7f; Proxy: null).`

**Comment by DarcyRaynerDD** [comment]
Hi @noahw3 . Thanks for the report. So, I downloaded the current version of the node layer, (version 49), which is what the plugin v2.17.0 attaches to your function. It's about 5.5mb zipped, and 18.4mb unzipped. Version 41 of the layer, which is what the plugin v2.12.0 attaches, is 5mb zipped and 14.8mb unzipped. One thing that might be worth trying, is if using the latest version of the plugin you configure `addLayers` to false, and manually add the older layer, does the deploy still fail? eg:

```yaml
custom:
  datadog:
    addLayers: false

functions:
  node:
    # ....
    layers:
      - arn:aws:lambda:${self:provider.region}:464622532012:layer:Datadog-Node12-x:41

```

**Comment by noahw3** [comment]
That 4 MB difference would explain why the bloated version worked with the old version. With that in mind I went back and tried again with v2.17.0 and it's working now, so I'm just going to chalk this up to serverless doing weird things.

Doesn't seem like an issue with this plugin specifically, sorry for the false report.
