### ISSUE TITLE
Clarify Behavior around `forwarderArn` option

### ISSUE THREAD

**Issue by jwyoungpm** [DataDog/serverless-plugin-datadog#119]
## Expected Behavior
[The documentation](https://www.serverless.com/plugins/serverless-plugin-datadog) for the `forwarderArn` states: 

> Setting this parameter subscribes the given Datadog forwarder to the Lambda functions’ CloudWatch log groups. Required when enableDDTracing is set to true. Do not set addExtension to true when using forwarderArn.

Because it its `Required`, we'd expect an error to be thrown. **WE ACTUALLY DO NOT WANT THIS BEHAVIOR**

## Actual Behavior

When something else has added the datadog forwarder - such as the Datadog AWS Integration - tracing works as expected. **WE ACTUALLY DO LIKE THIS BEHAVIOR**

We would like this to continue to be the case and not have the `forwarder` or `forwarderArn` be required. Right now, this works as desired but I'd like to have the docs changed to reflect that you just need SOMETHING to create the forwarder and not require it in serverless.yaml. 

Our use case: 

* We have dozens, maybe over a hundred lambdas - we have even more log groups
* Half of the lambdas are in serverless, the other half are in terraform, we also have non-lambda things generating logs
* We use the DD aws integtration to automatically subscribe our log groups to the forwarder
* We'd prefer to allow the DD AWS integration to handle subscription - if it is off, devs have to rememeber to add it, if its on but devs add this, there is a double subscription

**I am happy to open an MR to do this** but before I do, I just want to make sure there isn't some other reason to leave it as is. What we want to avoid is someone seeing that blurb, then seeing that serverless isn't enforcing that behavior, then updating serverless to enforce that behavior.

## Steps to Reproduce the Problem

  1. In serverless, create a lambda w/o tracing or a sub filter
  2. Outside of serverless, create a subscription filter to a datadog forwarder
  3. In serverless, specific `enableDDTracing: true`, do not specifiy `forwarder` or `forwarderArn`, trace any function
  4. Deploy and test tracing -> this will deploy and trace w/o error

## Specifications

  - Serverless Framework version: 1.78.1
  - Datadog Serverless Plugin version: 2.17.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Python 3.8

**Comment by DarcyRaynerDD** [comment]
Hi @jwyoungpm, this is a good catch. We do intend to continue supporting forwarder subscriptions outside of the plugin, and don't intent to make 'forwarder' or 'forwarderARN' mandatory fields. This looks like a mistake in our documentation, I think what that sentence was trying to convey is that you must subscribe our forwarder somehow to get tracing without the extension. We'll update the wording.
