### ISSUE TITLE
Unit tests Erroring Out without throwing errors

### ISSUE THREAD

**Issue by samchungy** [DataDog/serverless-plugin-datadog#157]
## Expected Behavior
I was working on a PR for something and noticed that there are some unit tests which are very broken but the jest tests are still passing.

![image](https://user-images.githubusercontent.com/18017094/129723031-73e3a6a4-725a-4521-add5-e81631d1035c.png)

![image](https://user-images.githubusercontent.com/18017094/129723085-d0719167-3e56-48e1-b76c-4efe9b437421.png)

```
expect(async () => await searchMonitors("queryString", "apikey", "appkey")).rejects.toThrowError(
      "Could not perform request due to invalid authentication",
    )
```

will not throw an error and will just pass.

in fact it's throwing an error as is but jest won't throw it.

```
Expected substring: "Could not perform request due to invalid authentication"
Received message:   "response.json is not a function"
```

I would fix it, but I am fairly time poor.

When you switch it to the proper syntax eg. this it will fail properly
```
await expect(searchMonitors("queryString", "apikey", "appkey")).rejects.toThrowError(
      "Could not perform request due to invalid authentication",
);
```

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Serverless Framework version: 
  - Datadog Serverless Plugin version: 
  - Lambda function runtime (Python 3.7, Node 10, etc.): 
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by astuyve** [comment]
Thanks for this issue @samchungy! I'll close this issue when I can release and publish a new version.
