### ISSUE TITLE
Install extension layer on unsupported runtimes

### ISSUE THREAD

**Issue by chrislentz** [DataDog/serverless-plugin-datadog#160]
It would be great if the plugin were to install the extension layer for UNSUPPORTED languages like GO. I understand that it doesn't have a runtime specific layer and I would still be required to use `go get`, but it would be awesome if the plugin would save me from having to do the below for UNSUPPORTED runtime functions.

```
layers:
    - arn:aws:lambda:#{AWS::Region}:464622532012:layer:Datadog-Extension:X
```

**Comment by astuyve** [comment]
Hi @chrislentz - thanks for reaching out!
I'm not sure I understand your use case here. The lambda extension will not execute in unsupported runtimes ([docs](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html)), and our extension is basically a binary that interacts with other Datadog libraries, so I'm not aware the extension can actually do anything in an unsupported runtime.

Can you help me understand what you're trying to get from the extension layer?

**Comment by astuyve** [comment]
Closing as there's been no reply for over 30 days. Please re-open if needed!
