### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by azai91** [DataDog/serverless-plugin-datadog#17]
## Expected Behavior
It would be great to have support with the typescript serverless plugin (generate .ts files instead of .js files in datadog handler)

## Actual Behavior
An error is thrown where the typescript plugin is looking for ts files but the dd plugin only generates .js files.

## Steps to Reproduce the Problem

  1. sls deploy --noDeploy in a typescript project with the typescript and dd plugin
## Specifications

  - Serverless Framework version: 
  - Datadog Serverless Plugin version: 
  - Lambda function runtime (Python 3.7, Node 10, etc.):  Node 10
  
## Stacktrace
  
  ```
Serverless: Auto instrumenting functions with Datadog
Serverless: Adding Lambda Layers to functions
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
{ file: undefined,
  start: undefined,
  length: undefined,
  messageText:
   "File 'datadog_handlers/clear-business-credits.ts' not found.",
  category: 1,
  code: 6053,
  reportsUnnecessary: undefined }

  Type Error ---------------------------------------------

  TypeError: Cannot read property 'getLineAndCharacterOfPosition' of undefined
  ```

**Comment by DarcyRaynerDD** [comment]
Hi azai91, sorry for the late reply. We just released a version that should be compatible with serverless-plugin-typescript, (v0.13.0). If you get a chance, we'd love to hear any feedback on whether this solves your issue.
