### ISSUE TITLE
Monitors do not get created, without error, probably due to eu site

### ISSUE THREAD

**Issue by devnoo** [DataDog/serverless-plugin-datadog#170]
## Expected Behavior
High error count monitor created

## Actual Behavior
I setup the serverless plugin and added the high error count monitor.
but no monitor appears, i think it is due to the monitoring api class not using the site configuration param, but using datadog.com

## Steps to Reproduce the Problem

  1. setup high_error_count monitor 
  1. go to datadoghq.eu
  2.go to monitors, 
 3. monitor does not show upo
  

## Specifications

  - Serverless Framework version: 2.44
  - Datadog Serverless Plugin version: 2.31.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): python
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by devnoo** [comment]
hi guys, anyone has had a look, it is preventing us from finishing datadog trial.

**Comment by DarcyRaynerDD** [comment]
Hi @devnoo. Thanks for the report. A fix for the DD_SITE/monitors bug will be available in the next release, (which should be some time in the next week).

**Comment by jcstorms1** [comment]
Hey @devnoo just wanted to follow up and let you know we have released a new version that includes the above fix. If you continue to experience an issue please let us know.
