### ISSUE TITLE
Function arn is not lowercased after version 2.31.0

### ISSUE THREAD

**Issue by ragibsm** [DataDog/serverless-plugin-datadog#193]
## Expected Behavior

Before updating serverless-plugin-datadog version to the latest (3.1.1) from 2.31.0, function arns were lowercased. For example If you had a lambda called "example-lambdaName" plugin would make this name lowercased (example-lambdaname) before pushing the logs to DataDog

## Actual Behavior

In version 3.1.1 function arn is not lowercased so if the function is named "example-lambdaName" function arn will be unchanged. This seems to break things in DataDog as I'm not able to see function logs when I click on specific function invocation. Also "MEMORY USED" column is empty. With version 2.31.0 all of this was working fine.

## Steps to Reproduce the Problem

  1. Deploy a lambda named in camel case notation with the serverless-plugin-datadog@3.1.1
          
![image](https://user-images.githubusercontent.com/73938530/138283606-24fb8d8d-89dc-42b9-b9d0-e6b8940cc2e4.png)

  2. After you run the lambda click on the lambda invocation in DataDog. You won't be able to see the function logs in the window that pops up on the right side. Also "MEMORY USED" column will be "-".
 

## Specifications

  - Serverless Framework version:  2.63.0
  - Datadog Serverless Plugin version: 3.1.1
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14

**Comment by tianchu** [comment]
@ragibsm sorry for that, we did notice that fix was missed in the v12 release, and it should be now included in v13. I will release a new version of the plugin to bump up the extension version to 13 shortly.

**Comment by astuyve** [comment]
Released in 3.2.0
