### ISSUE TITLE
When used with warmup plugin, shows cold starts

### ISSUE THREAD

**Issue by bendubuisson** [DataDog/serverless-plugin-datadog#199]
## Expected Behavior
The Warm up plugin (https://github.com/juanjoDiaz/serverless-plugin-warmup) is calling my lambda every 5 minutes to keep it warm. I can confirm that because I can see the calls in the logs.
Somehow, my function is still reporting cold starts intermittently. Now I can see it being invoked at least every 5 minutes so maybe there's an issue and they are not really cold starts?

```
{
    "dd.version": "",
    "dd.env": "",
    "dd.service": "",
    "dd.trace_id": "xxxxx",
    "dd.span_id": "xxxxx",
    "level": "INFO",
    "location": "wrapper:87",
    "message": "WarmUp - Lambda is warm!",
    "timestamp": "2021-11-02 01:35:29,267+0000",
    "service": "my-service",
    "environment": "test",
    "cold_start": true,
    "function_name": "my-function",
    "function_memory_size": "512",
    "function_arn": "arn:aws:lambda:xxxxx",
    "function_request_id": "xxx-xxx-xxx-xxx",
    "xray_trace_id": "xxx-xxx-xxx-xxx"
}
```

**Comment by astuyve** [comment]
Hi @bendubuisson - even polling your function every 5 minutes won't guarantee missing cold starts.
We identify cold starts by setting a variable outside of the handler function and seeing if it's set on subsequent calls. If it's not set - the invocation is a cold start. If it is, the invocation is not.

You can verify this behavior yourself using datadog logs or cloudwatch logs. Look for `init duration`. If it's present, then the invocation is a cold start.
Note these two invocations (one cold, one warm):
![image](https://user-images.githubusercontent.com/1598537/139922821-ffd7f4d8-be83-42b5-9cfc-310b1997a394.png)

If you're still seeing cold starts flagged in the application, but not `Init Duration` in the logs, please report back. Thanks!

**Comment by bendubuisson** [comment]
Thank you for the explanation, that actually makes sense. Our warmup plugin is probably only keeping that one instance alive and cold_starts probably apply when there are concurrent invocations.
