### ISSUE TITLE
Update serverless plugin to use latest version of datadog-lambda-layer-js (0.14.0)

### ISSUE THREAD

**Issue by benarena** [DataDog/serverless-plugin-datadog#20]
The serverless plugin currently uses version 0.10.0 of the datadog-lambda-layer-js. The [latest version](https://github.com/DataDog/datadog-lambda-layer-js/releases) is 0.14.0.

**Comment by DarcyRaynerDD** [comment]
Hi @benarena, the serverless plugin uses the latest layers that were available at the time of release, (so release 0.12.0 uses python layer version 11, and node version 14). I agree that it's confusing, in the future we will publish the layer versions along side our release notes.

**Comment by benarena** [comment]
I can confirm it is working as expected after upgrading to the newly released 0.12.0
