### ISSUE TITLE
Can I create monitors using serverless configs without setting up an AWS provider?

### ISSUE THREAD

**Issue by macsj200** [DataDog/serverless-plugin-datadog#208]
I'm using `serverless.ts` to define my infrastructure with TypeScript.

<details>

```typescript
const serverlessConfiguration: AWS = {
  service: "serverless",
  frameworkVersion: "2",
  custom: {
    datadog: {
      addLayers: true,
      monitorsApiKey: "{Datadog_API_Key}",
      monitorsAppKey: "{Datadog_APP_Key}",
      monitors: {
        custom_monitor_id: {
          name: "Custom Monitor",
          query:
            "max(next_1w):forecast(avg:system.load.1{*}, 'linear', 1, interval='60m', history='1w', model='default') >= 3",
          message:
            "Custom message for custom monitor. Notify @data.dog@datadoghq.com @slack-serverless-monitors",
          tags: ["custom_monitor", "serverless"],
          priority: 3,
          options: {
            enable_logs_sample: true,
            require_full_window: true,
            include_tags: false,
            notify_audit: true,
            notify_no_data: false,
            thresholds: {
              ok: 1,
              warning: 2,
            },
          },
        },
      },
    },
  },
  plugins: ["serverless-plugin-datadog"],
  provider: {
    name: "aws",
    runtime: "nodejs14.x",
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1",
    },
    lambdaHashingVersion: "20201221",
  },
};
```

<summary>
serverless config
</summary>
</details>

I would like to be able to use `serverless-plugin-datadog` **without** setting up any AWS functions/CloudFormation Templates/etc. It would be ideal if I could **remove** the `provider` definition in my config file as well.

For context, the app I'm working on **does not currently** have any AWS resources defined, though it _does_ use DataDog with manually configured monitors. I would like to be able to use a package like `serverless-plugin-datadog` to configure monitors with code without having to bring in AWS/the rest of the serverless framework.

Note: I _was_ able to fork the package and manually invoke the [`setMonitors()`](https://github.com/DataDog/serverless-plugin-datadog/blob/f41f233be686cfda4cf4a53fa268d010f5f572bb/src/monitors.ts#L144) function with a hardcoded payload and dummy values for `{ cloudFormationStackId, service, env }`. This indicates to me that it is indeed possible to use `serverless-plugin-datadog` independently of serverless/AWS.

I noticed that `setMonitors()` is called in the [`afterDeploy()`](https://github.com/DataDog/serverless-plugin-datadog/blob/master/src/index.ts#L149) function defined in `index.ts`. Is there a way to manually invoke the `afterDeploy()` function via serverless? I know that it runs _after deploy_ i.e. if I run `yarn serverless deploy` the AWS stack will deploy _then_ the datadog config runs. Is there a way to skip the "deploy" part of `serverless deploy`, something like `serverless deploy --onlyAfterDeployHooks`?

Thanks!

**Comment by astuyve** [comment]
Hi @macsj200 - I'm quite intrigued as to the application you're building with Serverless Framework which does not use AWS, but does not use any AWS resources.

Are you working on a serverless app in general? Or just using Serverless as a way to create a datadog monitor? It seems you've set environment variables and hashing versions for lambda functions, but you've mentioned your app doesn't use any AWS resources at all?

If you're not using any lambda functions at all, and are simply trying to create monitors, I think this feature may be more suited for the Datadog CLI, and I'd suggest opening a feature request there: https://github.com/DataDog/datadog-ci

If not, I'd like a bit more context to understand your use case. While `setMonitors()` is a thin wrapper around our API, the datadog plugin is not. We could explore adding another command to create monitors, but you might be better off simply hitting the API yourself.

**Comment by macsj200** [comment]
@astuyve thank you for the quick response! I have not evaluated `datadog-ci` yet, thanks for sharing that resource!

For context, the app **does not currently** use any AWS resources but it likely will _in the future_, so that's why I was looking into using serverless for this.

> you might be better off simply hitting the API yourself

That's a good suggestion and for an initial version we may end up doing this. All we really want is to define datadog monitors as "code" that we can easily integrate into CI/CD infrastructure (as an alternative to manually creating monitors via the datadog UI).

**Comment by astuyve** [comment]
Ah, I see. While it's technically possible to achieve what you've asked, unfortunately monitors as code is not the goal of this project, instead it seems best suited for the Datadog CLI, and thus we won't be pursuing it.

If you're still consider IAC providers, we do offer a terraform module that would accomplish this: https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor

Otherwise, I'd suggest opening a ticket in the Datadog CI repository, and in parallel exploring the [Datadog Monitors API](https://docs.datadoghq.com/api/latest/monitors/).

Thanks!
