### ISSUE TITLE
Help configuring DD_TRACE_EXTRACTOR with Webpack

### ISSUE THREAD

**Issue by nireak** [DataDog/serverless-plugin-datadog#213]
## Expected Behavior
Configure DD_TRACE_EXTRACTOR environment variable to point to the location of my extractor function: extractors.eventBridge

## Actual Behavior
Once deployed I got the following error: datadog:an error occurred while loading the custom trace context extractor. The errror also indicates:":{},"extractorEnv":"extractors.eventBridge"

## Steps to Reproduce the Problem

  1. Install  the plugins: serverless-webpack and serverless-plugin-datadog 
  2. create the "extractors.js" file exporting the eventBridge function according to [this documentation](https://docs.datadoghq.com/serverless/distributed_tracing/serverless_trace_propagation/?tab=eventbridge#sample-extractors)
  ```
export const eventBridge = (event, context) => {
    //exports.eventBridge = (event, context) => {
    const traceData = event.detail._datadog
    const traceID = traceData["x-datadog-trace-id"];
    const parentID = traceData["x-datadog-parent-id"];
    const sampledHeader = traceData["x-datadog-sampling-priority"];
    const sampleMode = parseInt(sampledHeader, 10);

    return {
        parentID,
        sampleMode,
        source: 'event',
        traceID,
    };
};
```
  3. Create an environment variable at serverless.yml: DD_TRACE_EXTRACTOR: extractors.eventBridge
  
  Note. I have tried to locate the extractors.js file at several places (the root, near the lambda functions, etc) without success.

## Specifications

  - Serverless Framework version: 2.68
         Framework Core: 2.68.0 (standalone)
         Plugin: 5.5.1
         SDK: 4.3.0
         Components: 3.18.1
  - Datadog Serverless Plugin version: v.3.4.0
  - Datadog Externsion Version: 16
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs12.x
  - Serverless-webpack: 5.6.0,
  - Webpack:  4.43.0,
  - Webpack-bundle-analyzer: 3.8.0,
  - Webpack-node-externals: 2.5.0
  
## Stacktrace
  No stack trace

**Comment by astuyve** [comment]
Hey @nireak - thanks for the report! I tried copying your extractor into an `extractor.js` file locally and received a syntax error:
```
Welcome to Node.js v12.7.0.
Type ".help" for more information.
> const eventBridge = require('./extractor.js')
Thrown:
/Users/aj.stuyvenberg/debug/extractor.js:1
export const eventBridge = (event, context) => {
^^^^^^

SyntaxError: Unexpected token export
```
After reviewing the documentation you linked to, I believe this can be resolved quickly.
Could you try replacing `export const eventBridge` with `exports.eventBridge` and trying again?
```
exports.eventBridge = (event, context) => {
  const traceData = event.detail._datadog
  const traceID = traceData["x-datadog-trace-id"];
  const parentID = traceData["x-datadog-parent-id"];
  const sampledHeader = traceData["x-datadog-sampling-priority"];
  const sampleMode = parseInt(sampledHeader, 10);

  return {
      parentID,
      sampleMode,
      source: 'event',
      traceID,
  };
};
```

Thanks!

**Comment by nireak** [comment]
Hi @astuyve  , thanks for the quick reply!

Sorry I didn't explain it previously with more detail but I had also tried using the code as in the example provided (using `exports.eventBridge` instead of `export const eventBridge` (one of the options was in the commented line) but the error persisted. I have tried it again now to double-check it.

Do you know where should I put the file? at the root? near the lambdas?

Perhaps the problem is related to the webpack plugin?
Thanks again for your assistance.

**Comment by astuyve** [comment]
Hey! Thanks for the quick response!
It should be at the same level of your serverless.yml file. To ensure webpack is including it, please run `sls package` and then unzip the resulting zip file and inspect the contents to make sure the `extractor` file is there.
Thanks!

**Comment by nireak** [comment]
Thank you very much @astuyve . Following your advice I checked that the `extractor.js` file was not included (my fault!!) due to a bad webpack configuration.

My original file was 
```js
// webpack.config.js
const slsw = require('serverless-webpack');

module.exports = {
  ...
  entry: slsw.lib.entries,
  ...
};
```
and it should had been:

```js
// webpack.config.js
const _ = require('lodash');
const slsw = require('serverless-webpack');

module.exports = {
  ...
  entry: _.assign({
    extractor: './extractor.js'
  }, slsw.lib.entries),
  ...
};
```

**Comment by astuyve** [comment]
Ah! Good find, I suspected webpack as likely due to the fact that your project never directly required the extractor. Glad you got it working!
