### ISSUE TITLE
Plugin always overrides DD_CAPTURE_LAMBDA_PAYLOAD environment variable set at Serverless YML

### ISSUE THREAD

**Issue by lmego** [DataDog/serverless-plugin-datadog#214]
## Expected Behavior
When setting the "DD_CAPTURE_LAMBDA_PAYLOAD" environment variable at the Serverless.yml file, the pluggin should always use that value

## Actual Behavior
The plugin always overrides the value set at the Serverless.yml file for the DD_CAPTURE_LAMBDA_PAYLOAD env variable and always sets it to FALSE. Therefore we are unable to override the value

## Steps to Reproduce the Problem

  1. Create a serverless function with this plugin and add the environment variable DD_CAPTURE_LAMBDA_PAYLOAD = true in the serverless yml
  2. Deploy the function and it will always be deployed with the DD_CAPTURE_LAMBDA_PAYLOAD env var = false

## Specifications

  - Serverless Framework version: 2.71.0
  - Datadog Serverless Plugin version: 3.5.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): 14.17.0
  - Webpack: 5.66.0
  - ServerlessWebpack: 5.6.0
  
## Stacktrace
  
No stack trace.

**Comment by agocs** [comment]
Hey @lmego , thanks for raising this issue. As a workaround, try adding `captureLambdaPayload` to the `custom.datadog` map, like so

```
 23 custom:
 24   datadog:
 25     captureLambdaPayload: true
 26     addExtension: true
 27     apiKey: ${env:DD_API_KEY}
```

In the mean time, I'll create a bug in our issue tracker to get this fixed.

**Comment by lmego** [comment]
Thank @agocs that works for me. It might be worth it to check some of the other env variables as well. For example,  the DD_MERGE_XRAY_TRACES env variable is also having the same issue. The incorrect behavior for that variable can also be temporarily overridden like so,
`
custom:
   datadog:
      enableXrayTracing: true
      addExtension: true
      apiKey: ${env:DD_API_KEY}
`

**Comment by astuyve** [comment]
Hi @lmego! thanks for this issue, it's being tracked here https://github.com/DataDog/serverless-plugin-datadog/issues/185

so I'll close this issue in favor of #185. Thanks!
