### ISSUE TITLE
Enabling Profiling Via Serverless Plugin

### ISSUE THREAD

**Issue by bjclark13** [DataDog/serverless-plugin-datadog#221]
Hi there!

From your documentation for https://docs.datadoghq.com/tracing/profiler/enabling/nodejs/?tab=environmentvariables, it looks like the profiler comes baked into datadog tracing. Is it possible to enable and configure profiling within this serverless plugin

I have tried adding the environment variable
```
    DD_PROFILING_ENABLED: true
```
to my `serverless.yml` but that does not seem to make a diference.

**Comment by tianchu** [comment]
@bjclark13 Thanks for your interests in profiling! Continuous profiling is NOT yet supported in the Lambda environment, but it is on our 2022 roadmap. Do you mind describing your use case, which may help guide our implementation?

**Comment by dforsl** [comment]
Hi! Any news here? We'd also like this for basic reasons such as finding where execution time is spent etc. in lambdas running NodeJS.

**Comment by astuyve** [comment]
Hi @dforsl - Profiling (in Beta) for nodejs and python is now available. Please use nodejs layer version 86 or python layer version 67

For now, this is enabled with `DD_PROFILING_ENABLED`, as you've tried previously.

I'll update this ticket when we add support to this library specifically.

**Comment by astuyve** [comment]
This is now available in beta for both NodeJS and Python, closed by https://github.com/DataDog/serverless-plugin-datadog/pull/358
