### ISSUE TITLE
Cannot exclude a function with DataDog serverless plugin

### ISSUE THREAD

**Issue by sahanmadusanka** [DataDog/serverless-plugin-datadog#230]
I'm having an issue with deploying lambda functions using the serverless framework. There is one lambda which is CloudFront edge function.

Using the "exclude" custom property, I have excluded that particular function. however, Datadog plugging still adding environment variables to the function and Cloudformation throws an error saying edge function cannot have environment variables.

How can I exclude the lambda function from the serverless.yml?

## Expected Behavior

When setting function in "exclude" inside custom.datadog, should not include DataDog lambda layer and environment variables 

## Actual Behavior

Even excluded function getting add lambda layer and environment variables 

## Steps to Reproduce the Problem

  1. Use version mentioned in blow specification 
  2. Deploy to AWS and CFT will fail due to edge lambda cannot have environment variables

## Specifications

  - Serverless Framework version: 1.55.1
  - Datadog Serverless Plugin version:  3.7.1
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 12
  
## Stacktrace
  
Serverless Error ---------------------------------------
 
  The function cannot have environment variables. Function: arn:aws:lambda:us-east-1:000000:function:liberty-web-request-controller-dev:439
  ```

**Comment by astuyve** [comment]
Hi @sahanmadusanka can you share a redacted copy of your `serverless.yml` file? I tried reproducing this with Serverless v3 and serverless-plugin-datadog v3.7.1 and wasn't able to reproduce it with a `cloudFront` event, but perhaps I could with serverless v1.55.1.

Thank you!

**Comment by astuyve** [comment]
Ah this may be an issue with `pre-existing-cloudfront`. I'll dig in. Thanks @sahanmadusanka!

**Comment by sahanmadusanka** [comment]
Defining "exclude | addExtension" properties in the serverless.yml with the custom section will work as expected. However API key is picking up from the custom-var-configs.yml file.

Thanks!

**Comment by astuyve** [comment]
Hi @sahanmadusanka - I cannot reproduce the API key issue with `exclude`, even using Serverless 1.55.
Here is my example:
```yaml
service: exclude-function
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    FOOBAR: blah

custom:
  datadog:
    exclude:
      - hello
    apiKey: "asdfasdfasdf"
    addExtension: true
    addLayers: true

functions:
  hello:
    handler: handler.hello
    events:
      - cloudFront:
          eventType: viewer-response
          origin: s3://bucketname.s3.amazonaws.com/files

  goodbye:
    handler: handler.hello
    events:
      - httpApi:
          path: /goodbye
          method: GET

plugins:
  - serverless-plugin-datadog
```

The resulting cloudformation for `hello`, which is excluded, does not contain any environment variables:
```json
"HelloLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "serverless/exclude-function/dev/1645808797928-2022-02-25T17:06:37.928Z/exclude-function.zip"
        },
        "FunctionName": "exclude-function-dev-hello",
        "Handler": "handler.hello",
        "MemorySize": 128,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "nodejs12.x",
        "Timeout": 5,
        "Environment": {
          "Variables": {
            "FOOBAR": "blah"
          }
        }
      },
      "DependsOn": [
        "HelloLogGroup",
        "IamRoleLambdaExecution"
      ],
      "DeletionPolicy": "Retain"
    }
```


Compared to the Goodbye function, which does:
```json
    "GoodbyeLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "serverless/exclude-function/dev/1645808797928-2022-02-25T17:06:37.928Z/exclude-function.zip"
        },
        "FunctionName": "exclude-function-dev-goodbye",
        "Handler": "/opt/nodejs/node_modules/datadog-lambda-js/handler.handler",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "nodejs12.x",
        "Timeout": 6,
        "Tags": [
          {
            "Key": "dd_sls_plugin",
            "Value": "v3.7.1"
          },
          {
            "Key": "service",
            "Value": "exclude-function"
          },
          {
            "Key": "env",
            "Value": "dev"
          }
        ],
        "Environment": {
          "Variables": {
            "FOOBAR": "blah",
            "DD_API_KEY": "asdfasdfasdf",
            "DD_SITE": "datadoghq.com",
            "DD_TRACE_ENABLED": true,
            "DD_LOGS_INJECTION": true,
            "DD_SERVERLESS_LOGS_ENABLED": true,
            "DD_CAPTURE_LAMBDA_PAYLOAD": false,
            "DD_MERGE_XRAY_TRACES": false,
            "DD_LAMBDA_HANDLER": "handler.hello"
          }
        },
        "Layers": [
          "arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node12-x:70",
          "arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:20"
        ]
      },
      "DependsOn": [
        "GoodbyeLogGroup",
        "IamRoleLambdaExecution"
      ]
    },
```

Can you confirm this on your side? Is there a way you can provide a reproducible example?

Thanks!

**Comment by astuyve** [comment]
Hi @sahanmadusanka - we received your uploaded zip files, thanks!

The issue is that you're pushing the Datadog configuration into a `var` block of `custom`, so it lives at `self:custom.var.datadog`. But this plugin expects to find configuration in `custom.datadog`, so the configuration is not valid.

As a workaround, I'd suggest simply defining the block as:
```
custom:
  datadog: ${file(resources/custom-var-configs.yml):datadog}
```

**Comment by astuyve** [comment]
Great, thanks!
