### ISSUE TITLE
Error 'datadog:api key not configured' when using apiKeySecretArn

### ISSUE THREAD

**Issue by aline-camargo** [DataDog/serverless-plugin-datadog#237]
## Expected Behavior
Sending monitoring data without logging errors, as it is configured according to documentation.

## Actual Behavior
On every instance start we are getting this `datadog:api key not configured` error. All APM data and logs are being sent normally, but I believe this behavior of throwing error is not expected, as it was a false warning.

When I changed my code to use the `apiKey` parameter instead of `apiKeySecretArn` the error stoped showing.

## Steps to Reproduce the Problem

  1. Pass the key to dd extension using the apiKeySecretArn parameter
  2. Observe the error log on every instance start

## Specifications

  - Serverless Framework version:  2.72.2
  - Datadog Serverless Plugin version: 3.7.1
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14
  
## Stacktrace
  
  ```
  2022-03-08T13:22:09.277Z	undefined	ERROR	{"status":"error","message":"datadog:api key not configured, see https://dtdg.co/sls-node-metrics"}
  ```
![image](https://user-images.githubusercontent.com/54282898/157247405-8af61e52-b802-42c0-b34a-794ff4ab7946.png)

**Comment by tianchu** [comment]
@astuyve I think we should also `logDebug` if `this.isAgentRunning` (similar to when forwarder is used, in this case, extension should check for the api key, not this library) https://github.com/DataDog/datadog-lambda-js/blob/436650bad8f544332ac45767a4b202c2ee36e312/src/metrics/listener.ts#L186
