### ISSUE TITLE
Please fix open security vulnerability for simple-git

### ISSUE THREAD

**Issue by trygve-aaberge-adsk** [DataDog/serverless-plugin-datadog#240]
There is currently an [open security vulnerability for simple-git < 3.3.0](https://github.com/advisories/GHSA-3f95-r44v-8mrg). The latest release of serverless-plugin-datadog depends on simple-git `^2.48.0` so it's vulnerable.

I see there's an [open PR from dependabot](https://github.com/DataDog/serverless-plugin-datadog/pull/239) to upgrade it. Could you merge that and make a new release please?

**Comment by astuyve** [comment]
Sure thing!

**Comment by astuyve** [comment]
Published in 4.1.2

**Comment by trygve-aaberge-adsk** [comment]
Thanks!
