### ISSUE TITLE
Supports logs transfer in Rust (and other custom runtime)

### ISSUE THREAD

**Issue by kyfk** [DataDog/serverless-plugin-datadog#243]
## Expected Behavior

When `subscribeToAccessLogs` flag is true, the logs of rust runtime functions have been subscribed to the DataDog forwarder.

## Actual Behavior

Creating not supported runtime subscription filters is ignored.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Serverless Framework version: 
  - Datadog Serverless Plugin version: 
  - Lambda function runtime (Python 3.7, Node 10, etc.): 
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by astuyve** [comment]
Released in 4.2.0

**Comment by kyfk** [comment]
Thank you!
