### ISSUE TITLE
Error "datadog:api key not configured" even though apiKeySecretArn is set

### ISSUE THREAD

**Issue by philipwigg** [DataDog/serverless-plugin-datadog#246]
## Expected Behavior

If I have `apiKeySecretArn` configured and the plugin is able to read the DD API key, I do not get an error in the logs complaining that

```
datadog:api key not configured, see https://dtdg.co/sls-node-metrics
```

## Actual Behavior

I do receive an error that

```datadog:api key not configured, see https://dtdg.co/sls-node-metrics```

even though I don't need it to be configured because I'm using `apiKeySecretArn` as an alternative.

## Specifications

  - Serverless Framework version: 3.10.-
  - Datadog Serverless Plugin version: 4.1.2
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14

**Comment by astuyve** [comment]
Hi @philipwigg - thanks for reaching out!
This message comes from [dd-lambda-js](https://github.com/DataDog/datadog-lambda-js)

We did just release a [fix](https://github.com/DataDog/datadog-lambda-js/pull/273) for this, but I think it landed in 4.2.0 of this plugin (released only yesterday).

Would you mind upgrading to the latest version, and then confirm you're using v5.75 of datadog-lambda-js, or version 75 of the Datadog NodeJS Lambda Layer?

Thank you!

**Comment by philipwigg** [comment]
I'm not sure how to check the Lambda layer version, how do I do that?

I wonder if maybe `this.isAgentRunning` is still undefined at the point that the `getAPIKey` method is called? `getAPIKey` is called by the constructor whereas ``this.isAgentRunning` seems to be set only when `onStartInvocation` is called? I am not much of a developer so sorry if this is totally wrong!

https://github.com/DataDog/datadog-lambda-js/blob/42f89c3294aaa261a1bd1c9768c40840fbada70b/src/metrics/listener.ts#L184

**Comment by astuyve** [comment]
Hi @philipwigg! The easiest way is to log into the AWS console, go to the Lambda function, and then inspect the `Layers` section. A screenshot would be sufficient.

Thanks!

**Comment by philipwigg** [comment]
Sure, here you go 

![image](https://user-images.githubusercontent.com/244059/161296528-6ddb3377-21b2-4562-a275-3f3622889a8b.png)

**Comment by astuyve** [comment]
Okay thanks - I'll look into this and get back to you!

**Comment by astuyve** [comment]
Hi @philipwigg - there are a few things occurring here. It appears that `apiKeySecretArn` is not yet supported by `datadog-lambda-js`, which is why you're seeing the error.

This is only relevant to you if you're using `sendDistributionMetricWithDate`, which hits the API directly. Otherwise metrics are flushed to the extension (where `apiKeySecretArn` is supported).

We need to make several additional changes to support `apiKeySecretArn`. In the meantime, we should move this issue to https://github.com/DataDog/datadog-lambda-js
