### ISSUE TITLE
Logs not working for some lambdas

### ISSUE THREAD

**Issue by chanan** [DataDog/serverless-plugin-datadog#256]
## Expected Behavior
Logs should appear in datadog for all serverless projects that utilize serverless-plugin-datadog

## Actual Behavior
Some logs for some functions do not appear in datadog

## Steps to Reproduce the Problem

Not sure, but I suspect (haven't fully reproduced yet) that when using https://github.com/getlift/lift - Queue Construct, the logs don't work.

## Specifications

  - Serverless Framework version: 3.12.0
  - Datadog Serverless Plugin version: 4.3.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs14.x
  - "serverless-lift": "1.14.0"
  
## Stacktrace

n/a

**Comment by astuyve** [comment]
Hi @chanan - Thanks for reaching out!
This plugin doesn't yet support Lift, and can't claim to support all plugins available to the Serverless Framework, as there are far too many to support.

That said, we can consider this a feature request.

Thanks!

**Comment by chanan** [comment]
Is there a workaround to get the logs from cloudwatch into datadog?

**Comment by astuyve** [comment]
I'd suggest using the datadog lambda extension (with `addExtension: true` in the `datadog` config block) as an alternative. That doesn't rely on cloudwatch for lambda logs, and instead transmits logs asynchronously via the agent.

**Comment by astuyve** [comment]
Closing this as we are encouraging users to utilize the Datadog Extension, and therefore are not planning to support log forwarding automatically for Lift (if users still need to use the Forwarder, they can still manually subscribe using the Lambda integration tile in Datadog).
