### ISSUE TITLE
Metrics seem not to be reported correctly for some timed out Lambdas

### ISSUE THREAD

**Issue by chriszs** [DataDog/serverless-plugin-datadog#257]
## Expected Behavior

Datadog logs and metrics should match the Lambda report line for the request in CloudWatch, even when the Lambda times out after 15 seconds.

## Actual Behavior

Getting a different set of metrics in the Datadog Serverless logs and metric monitoring for some requests than what we're seeing in CloudWatch.

Seeing this sort of discrepancy for a couple invocations that timed out after 15 seconds:

<img width="1485" alt="Screen Shot 2022-04-29 at 4 25 27 PM" src="https://user-images.githubusercontent.com/1103467/166064374-18f14465-2a90-414a-9e33-78eb6b0a2ad6.png">

No errors are recorded, even though those invocations timed out, and the duration doesn't seem to be correctly reflected in the duration metrics.

Here's what the non-enhanced (presumably without the agent reporting) metrics look like:

<img width="1085" alt="Screen Shot 2022-04-29 at 3 17 35 PM" src="https://user-images.githubusercontent.com/1103467/166064522-0d0a42a1-9ae7-474b-8c69-3abf22e12936.png">

And the enhanced ones for the same Lambda function:

<img width="1032" alt="Screen Shot 2022-04-29 at 3 17 18 PM" src="https://user-images.githubusercontent.com/1103467/166064536-2e6be95d-1985-4a2c-9f4d-a0353d64c5d8.png">

## Steps to Reproduce the Problem

  1. Added the Serverless plugin to our Serverless.yml and configured it
  2. Noticed errors in CloudWatch
  3. Looked for them in Datadog and couldn't find them (at least in the enhanced charts, see above)
  4. Found the errored invocations in our CloudWatch logs
  5. Searched for the same request ID in Datadog logs
  6. Encountered the above discrepancy

## Specifications

  - Serverless Framework version: 2.72.3
  - Datadog Serverless Plugin version: 5.0.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): python3.7

## Additional details

I noticed the log agent shut down just before the timeout:

<img width="614" alt="Screen Shot 2022-04-29 at 4 31 44 PM" src="https://user-images.githubusercontent.com/1103467/166065162-24299410-5f4e-4f9b-8780-4f8877a35bd7.png">

This seems to be the case in a couple places. Wondering if it has anything to do with start up behavior.

**Comment by tianchu** [comment]
@chriszs the issue you flagged is very valid, we would love to take a deeper look into it! However, do you mind moving the issue to https://github.com/DataDog/datadog-lambda-extension or file a support ticket instead? I just don't think this issue has anything to do with the plugin. Thank you! 🙏
