### ISSUE TITLE
Lambda throws 'Maximum call stack size exceeded' error when using Datadog Lambda Extension

### ISSUE THREAD

**Issue by jessgoldq4** [DataDog/serverless-plugin-datadog#259]
## Expected Behavior
 
- Lambda code functions as expected.
- Lambda output logs to datadog as expected.

## Actual Behavior

- ❌ Lambda throws `Maximum call stack size exceeded` error upon invocation. 
- ✅ Lambda output logs to datadog as expected.

## Steps to Reproduce the Problem

  1. install v5.0.0 of `serverless-plugin-datadog`
  2. update serverless.yml:

```
plugins:
  - serverless-plugin-datadog
  - serverless-webpack
  - serverless-offline-local-authorizers-plugin
  - serverless-offline
```

```
custom:   
  datadog:
    site: datadoghq.com
    apiKey: ${env:DATADOG_API_KEY, ''}
```

3. run sls deploy

## Specifications

  - Serverless Framework version: 3.7.1
  - Datadog Serverless Plugin version: 5.0.0
  - Lambda function runtime: Node 14.19.0 | highest supported version by aws
  
## Stacktrace
  
```
{
    "errorType": "RangeError",
    "errorMessage": "Maximum call stack size exceeded",
    "stack": [
        "RangeError: Maximum call stack size exceeded",
        "    at emitInitNative (internal/async_hooks.js:210:5)",
        "    at emitInitScript (internal/async_hooks.js:493:3)",
        "    at process.nextTick (internal/process/task_queues.js:133:5)",
        "    at Channel.publish (diagnostics_channel.js:58:17)",
        "    at ServerResponse.emit (/opt/nodejs/node_modules/dd-trace/packages/datadog-instrumentations/src/http/server.js:33:24)",
        "    at onFinish (_http_outgoing.js:792:10)",
        "    at Object.write (/var/task/node_modules/@vendia/serverless-express/src/response.js:124:11)",
        "    at ServerResponse._writeRaw (_http_outgoing.js:351:17)",
        "    at ServerResponse._send (_http_outgoing.js:327:15)",
        "    at ServerResponse.end (_http_outgoing.js:849:10)"
    ]
}
```

**Comment by tianchu** [comment]
@jessgoldq4 Thanks for reporting the issue! However, I don't think this issue has anything to do with the plugin itself. It appears to be related to https://github.com/DataDog/dd-trace-js. Do you mind moving the issue over there? Or you can file a support ticket to Datadog for us to take a deeper look at your issue. Thanks 🙏

**Comment by jessgoldq4** [comment]
@tianchu Thanks for responding. So there's nothing wrong with my ordering of the serverless plugins?
