### ISSUE TITLE
Allow to add tags when using forwarder setup via AWS Integration tile

### ISSUE THREAD

**Issue by ifeltsweet** [DataDog/serverless-plugin-datadog#263]
## Expected Behavior

We are using the Datadog AWS Integration to [automatically subscribe to lambda log groups](https://docs.datadoghq.com/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function/?tab=awsconsole#set-up-triggers).

> Datadog automatically retrieves the log locations for the selected AWS services and adds them as triggers on the Datadog Forwarder Lambda function. Datadog also keeps the list up to date.

Such setup should not require specifying a `forwarderArn` for this plugin to manage subscriptions as they are managed automatically by the Datadog AWS Integration.

In version `3.x` this used to work well because there was `enableTags` setting which instructed this plugin to tag resources with `service` and `env` even if `forwarderArn` was not configured.

## Actual Behavior

In `5.0.1` this setting is applied only if `forwarderArn` is supplied. We would like to avoid supplying `forwarderArn` as it adds unnecessary complications for us.

## Specifications

  - Serverless Framework version: 3.17.0
  - Datadog Serverless Plugin version: 5.0.1
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14

**Comment by tianchu** [comment]
Sorry for the confusion. We need to update the readme a bit more about upgrading to 5.x.x in terms of tagging. Anyway, you don't need to set `forwarderArn` in order to apply the tags, instead you can set the `service` and `env` parameters (new in 5.x.x).

**Comment by lizapressman** [comment]
Fix is merged, please reopen if you continue to see problems
