### ISSUE TITLE
Malformed tag string with tags not separated by comma or space

### ISSUE THREAD

**Issue by tamirshaul** [DataDog/serverless-plugin-datadog#280]
Hey! 
We are getting errors in our CloudWatch log when running with version `v5.2.0`.

The issue caused by #273.

With the new version `v5.2.0` `git.repository_url` has been added to `DD_TAGS` and now it looks like this:
```
DD_TAGS=git.commit.sha:8609584c43a4583bf30ea531841601ef1fcab22f,git.repository_url:http://bitbucket.org/xxxx/repo-name
```
This causes this error in CloudWatch:
```
[ERROR]	2022-06-23T09:13:42.374Z		
Malformed tag string with tags not separated by comma or space 'git.commit.sha:8609584c43a4583bf30ea531841601ef1fcab22f,git.repository_url:http://bitbucket.org/xxxx/repo-name.
```
It happens because the `git.repository_url` value isn't quoted and contains ':' which causes `dd_trace` to think it is the beginning of a new tag and that the tags aren't separated by comma as expected.

## Expected Behavior
Tags should be inserted as quoted or in a viable format for `dd_trace`.

## Actual Behavior
Tags contains special characters which causes `dd_trace` to error.

## Steps to Reproduce the Problem

  run `serverless deployz` from bitbucket with `serverless-plugin-datadog` in version `v5.2.0` and make sure `enableSourceCodeIntegration` isn't set to `false` (it is `true` by default)
 
## Specifications
Our env:
deploying through bitbucket using the extension with the latest version.

  - Serverless Framework version: v2.7.0
  - Datadog Serverless Plugin version: v5.2.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Python 3.9

**Comment by bissli82** [comment]
@tamirshaul, Confirmed, same here, thx for raising this, let's hope a fix is out ASAP

**Comment by IvanTopolcic** [comment]
Thanks for reporting, will release a fix shortly for this.

**Comment by IvanTopolcic** [comment]
It seems that quoting the value doesn't actually solve the issue during my tests. I'm going to check in with the team that owns this and ask them what they recommend. I don't believe we officially support colons in tags (they get converted to underscores iirc) so I'm not sure what the expected behavior is here.

Just to confirm, this isn't blocking your deployments or causing bad behavior during the lambda invocation, correct? This problem should be a no-op, aside from that warning message

**Comment by tamirshaul** [comment]
Hey @IvanTopolcic thanks for responding so quickly.
Yes, I can confirm that this isn't blocking our droyment and does not cause any bad behavior in the lambda invocation side.
Only the error message.

The hotfix we applied until this is fixed in case anyone needs:

Set `custom.datadog.enableSourceCodeIntegration: false` in your `serverless.yml` file.

This disables the `DD_TAGS` entirely (including the commit sha)

Another alternative is to work with `v5.1.0`.

**Comment by IvanTopolcic** [comment]
Awesome, thanks for the follow up. Sometime to note is that source code integration should still work without the repository URL, so I'd recommend leaving it in if the message doesn't bother you, or downgrading to v5.1.0.

**Comment by IvanTopolcic** [comment]
@tamirshaul could you please upgrade to 5.2.1 and let me know if this fixes the issue?

**Comment by tamirshaul** [comment]
Hey @IvanTopolcic, Yes! it seems like everything works as expected now! 
thanks!

**Comment by chubzor** [comment]
@IvanTopolcic 
I've got the same issue running serverless plug-in v 5.6.0 on my serverless deployment.
+ serverless-plugin-datadog@5.6.0
+ serverless@3.22.0

The function runs but the immediate AWS lambda console response is an error:
Malformed tag string with tags not separated by comma or space 'git.commit.sha:git@github.com:Orgname/repo-name.git,<hash>'.

**Comment by schwartzman** [comment]
This issue is still present in 5.7.0.

**Comment by liamoneill** [comment]
Can confirm that my company is also encountering this bug with the same versions as @tamirshaul 
- serverless-plugin-datadog@5.6.0
- serverless@3.22.0

While the actual impact is just logging an error, it does create a fair amount of noise.

**Comment by IvanTopolcic** [comment]
Hi! It looks like this issue was caused by a breaking change in [datadog-ci](https://github.com/DataDog/datadog-ci) which was reported as minor version bump. I'm going to go ahead and cut a new release of the plugin which fixes the version of `datadog-ci` to `1.8.0` instead of `^1.8.0` so that this doesn't happen again. Sorry for the trouble folks!

**Comment by IvanTopolcic** [comment]
I've just gone ahead and released version v5.7.1 which should fix this. To note though, this is actually a similar yet separate issue from the original.

cc @schwartzman @liamoneill @chubzor

**Comment by liamoneill** [comment]
Can confirm that `v5.7.1` has fixed this issue for us. Thanks for the speedy fix @IvanTopolcic!

**Comment by schwartzman** [comment]
Fix confirmed. Thank you!

**Comment by IvanTopolcic** [comment]
Glad I could help 😄 going to mark this as resolved, this time hopefully for good 🤞
