### ISSUE TITLE
enableSourceCodeIntegration over-rides `datadog.custom.tags`

### ISSUE THREAD

**Issue by stephen-harris** [DataDog/serverless-plugin-datadog#283]
## Expected Behavior

With 
```
custom:
  datadog:
    ...
    enableSourceCodeIntegration: true
    tags: "foo:bar"
```

Lambdas are created with the `DD_TAGS` environment variable with value:

```
git.commit.sha:<hash>,git.repository_url:<url>,foo:bar
```

## Actual Behavior

Output: 
```
Adding Datadog Env Vars
Setting Datadog Forwarder
Warning: Datadog Lambda Extension and forwarder are both enabled. Only APIGateway log groups will be subscribed to the forwarder.
Adding Plugin Version 5.3.0 tag
Adding GitHub integration with git commit hash <hash> and remote <url>
```

The `custom.datadog.tags` are not included in `DD_TAGS`:

```
git.commit.sha:<hash>,git.repository_url:<url>
```

The `foo:bar` is initially set, but then `DD_TAGS` is [over-ridden](https://github.com/DataDog/serverless-plugin-datadog/blob/486fd9cafb45bf28eddbb9d0ac2c718a3fe568c2/src/index.ts#L408-L410). With `enableSourceCodeIntegration:false`, the `DD_TAGS` environment variable has the value `foo:bar` (as expected).

## Steps to Reproduce the Problem

  1. Set `custom.datadog.enableSourceCodeIntegration:true`
  1. Add tags to `custom.datadog.tags`

## Specifications

  - Serverless Framework version: 3
  - Datadog Serverless Plugin version: 5.3.0

**Comment by IvanTopolcic** [comment]
@stephen-harris could you upgrade to v5.3.1 and let me know if this fixes the issue?

**Comment by tianchu** [comment]
Closed assuming the fix worked.
