### ISSUE TITLE
400 error when trying to create a datadog monitor

### ISSUE THREAD

**Issue by bbrunodiad** [DataDog/serverless-plugin-datadog#293]
## Expected Behavior

Hi, I'm trying to create some datadog monitor. I have well added the DATADOG_API_KEY and DATADOG_APP_KEY as mentionned in the documentation as environment variable in my codebuild.

## Actual Behavior
I tried several syntaxes but I always get this error : 

`Error occurred when configuring monitors: 400 Bad Request: This could be due to incorrect syntax for test`

## Steps to Reproduce the Problem

  1. create a monitor with serverless

## Specifications

  - Serverless Framework version: 3.21.0
  - Datadog Serverless Plugin version: 5.4.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs16.x
  
## Stacktrace
  
  ```
monitors:
      - test:
          name: "Test"
          query: "sum(last_5m):sum:aws.apigateway.5xxerror{environment:prod,service:test}.as_count() > 0"
          message: "High rate error"
          #tags: ["test-test", "serverless","api-gateway"]
          #priority: 3
          options:
            #enable_logs_sample: true
            #require_full_window: true
            #include_tags: false
            #notify_audit: true
            #notify_no_data: false
            thresholds:
              ok: 1
              warning: 2
  ```

**Comment by agocs** [comment]
Hey @bbrunodiad , I think I've seen this before. Your `thresholds` needs `ok`, `warning`, and `critical`.

**Comment by bbrunodiad** [comment]
> Hey @bbrunodiad , I think I've seen this before. Your `thresholds` needs `ok`, `warning`, and `critical`.
> 
> If that doesn't fix it, we can dig in further.

Oh yes! 
```
Auto instrumenting functions with Datadog
--
127 | Skipping adding Lambda Library Layers, make sure you are packaging them yourself
128 | Adding Datadog Lambda Extension Layer to functions
129 | Adding Datadog Env Vars
130 | Adding Plugin Version 5.4.0 tag
131 | Adding Plugin Version 5.4.0 tag
132 | Error occurred when configuring monitors: 400 Bad Request: This could be due to incorrect syntax for test
133 | Datadog Monitoring

```
It still doesn't work but I'm going to try with the default monitor provided in the documentation!

Thank's for the help!

**Comment by bbrunodiad** [comment]
Hum, it works with the default one : 
```
Successfully created high_error_rate
```

**Comment by agocs** [comment]
Hey @bbrunodiad 

Under the hood, the Serverless plugin is making a call to the Datadog Monitors API. The API returns an error, but the Serverless plugin swallows that error and returns a different one. We've created a ticket to surface the error coming from the API.

In the mean time, you can try the request yourself. Here's an example for the configuration in the original issue:

```
curl -X POST "https://api.datadoghq.com/api/v1/monitor" \
-H "Content-Type: application/json" \
-H "DD-API-KEY: API-KEY-HERE" \
-H "DD-APPLICATION-KEY: APP-KEY-HERE" \
-d @- << EOF
{
  "name": "test",
  "message": "More than 10% of the function’s invocations were errors in the selected time range. Notify @data.dog@datadoghq.com @slack-serverless-monitors",
  "require_full_window": true,
  "options": {
    "thresholds": {
      "ok": 1,
      "warning": 2,
      "critical": 3
    }
  },
  "query": "sum(last_5m):sum:aws.apigateway.5xxerror{environment:prod,service:test}.as_count() > 0"
}
EOF
```

And the response:
```
{"errors": ["The parameter 'type' is required"]}%
```

**Comment by bbrunodiad** [comment]
Oh n

> Hey @bbrunodiad
> 
> Under the hood, the Serverless plugin is making a call to the Datadog Monitors API. The API returns an error, but the Serverless plugin swallows that error and returns a different one. We've created a ticket to surface the error coming from the API.
> 
> In the mean time, you can try the request yourself. Here's an example for the configuration in the original issue:
> 
> ```
> curl -X POST "https://api.datadoghq.com/api/v1/monitor" \
> -H "Content-Type: application/json" \
> -H "DD-API-KEY: API-KEY-HERE" \
> -H "DD-APPLICATION-KEY: APP-KEY-HERE" \
> -d @- << EOF
> {
>   "name": "test",
>   "message": "More than 10% of the function’s invocations were errors in the selected time range. Notify @data.dog@datadoghq.com @slack-serverless-monitors",
>   "require_full_window": true,
>   "options": {
>     "thresholds": {
>       "ok": 1,
>       "warning": 2,
>       "critical": 3
>     }
>   },
>   "query": "sum(last_5m):sum:aws.apigateway.5xxerror{environment:prod,service:test}.as_count() > 0"
> }
> EOF
> ```
> 
> And the response:
> 
> ```
> {"errors": ["The parameter 'type' is required"]}%
> ```

Oh nice, I'm going to try this!

**Comment by bbrunodiad** [comment]
After several investigation, I think that the problem come from my api key. I can't verify my monitor with your curl request, I get this error (the same I get from my codebuild deployment via serverless): 
`{"errors":["Forbidden"]}`

After some research, I found this : 
![image](https://user-images.githubusercontent.com/107848125/187443019-9745a3d2-983d-4ab0-80b9-aa2ced7e6ed9.png)

I tried to find out how to modify the scope of my api key but then I saw this : 
![image](https://user-images.githubusercontent.com/107848125/187443148-0fab7b1d-6ff9-45d1-bc37-acfc3eab5ea5.png)

I'm going to try to contact the support but I can't figured out how I am abble to create reserved monitor

**Comment by bbrunodiad** [comment]
It works! Thank's a lot!
