### ISSUE TITLE
v5.6.0 seems to break sls invoke

### ISSUE THREAD

**Issue by bfaulk96** [DataDog/serverless-plugin-datadog#294]
## Expected Behavior

```bash
> sls invoke --function migrations
```
should run successfully

## Actual Behavior

An error occurs and lambda invocation fails

## Steps to Reproduce the Problem

  1. Upgrade to `serverless-plugin-datadog@5.6.0`
  1. Run `sls invoke --function <functionName>` (I assume it's not specific to my migration function)

## Specifications

  - Serverless Framework version: `3.22.0`
  - Datadog Serverless Plugin version: `5.6.0`
  - Lambda function runtime (Python 3.7, Node 10, etc.): `nodejs16.x`
  
## Stacktrace
  
```bash
> sls invoke --function migrations

Warning: Using serverless deploy -f option only updates the function code and will not update CloudFormation stack (env variables included).
{
    "errorType": "TypeError",
    "errorMessage": "instrumentations[packageName] is not iterable",
    "trace": [
        "TypeError: instrumentations[packageName] is not iterable",
        "    at /opt/nodejs/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/register.js:25:66",
        "    at safeHook (/opt/nodejs/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/hook.js:20:12)",
        "    at Module.Hook.Module.require (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:114:33)",
        "    at require (node:internal/modules/cjs/helpers:102:18)",
        "    at Object.<anonymous> (/var/task/node_modules/tough-cookie/lib/cookie.js:32:11)",
        "    at Module._compile (node:internal/modules/cjs/loader:1105:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)",
        "    at Module.load (node:internal/modules/cjs/loader:981:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:822:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1005:19)"
    ]
}
```

**Comment by astuyve** [comment]
Thanks for reaching out @bfaulk96, I'll take a look at this and update you when I can reproduce. In the meantime please utilize an older version for now.

Thanks!

**Comment by astuyve** [comment]
Hi @bfaulk96 by chance are you using `stealthy-require`? Can you share your `package.json`?

I think this is related https://github.com/DataDog/dd-trace-js/issues/2307

I'll go ahead and cut a release of this the Javascript layer and this plugin which should clear this up for you.

**Comment by bfaulk96** [comment]
I wasn't explicitly using it, but an `npm ls` showed me that one of our deps is
```bash
  └─┬ node-vault@0.9.22
    └─┬ request-promise-native@1.0.7
      └── stealthy-require@1.1.1
```

Was the fix re-pushed as `5.6.0`?

**Comment by astuyve** [comment]
No it'll go out as 5.7.0, as dd-trace was also a minor (5.13 -> 5.14)

**Comment by astuyve** [comment]
This is now available: https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.7.0
