### ISSUE TITLE
git.repository_url was removed and now only git.commit.sha is added to the DD_TAGS

### ISSUE THREAD

**Issue by annerajb** [DataDog/serverless-plugin-datadog#309]
## Expected Behavior

DD_TAGS contains both git.commit.sha and git.repository_url
## Actual Behavior
only git.commit.sha is included

## Steps to Reproduce the Problem

  1. enable source code integration 
  1. (put breakpoints / deploy the lambda) you will see only the hash returned from the datadog-ci library 
  1. https://github.com/DataDog/serverless-plugin-datadog/commit/cea6e9a4e070b821c4ce4823ba8a2046b179ca57#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L409

## Specifications

  - Serverless Framework version: 3.23.0
  - Datadog Serverless Plugin version: 5.9.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): 
     node 16 (but this is when serverless packages) 
  
  
  
  Seems this commit removed it https://github.com/DataDog/serverless-plugin-datadog/commit/cea6e9a4e070b821c4ce4823ba8a2046b179ca57#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L409

[in this line the function returns](https://github.com/DataDog/serverless-plugin-datadog/blob/master/src/index.ts#L217)  both a remote and a githash but only the githash is used

**Comment by IvanTopolcic** [comment]
We removed this intentionally as it was a breaking some tracer libraries. Is this an issue for you? It should work fine without it.

**Comment by annerajb** [comment]
tracer library may work fine but this page asked for it to be configured 
is it no longer the case / not required and the documentation incorrect?
Which tracer libraries did it affect?
https://docs.datadoghq.com/integrations/guide/source-code-integration/?tab=github#configure-repositories

**Comment by IvanTopolcic** [comment]
Let me confirm what will break without it, but as of right now it can actually break your tagging.

**Comment by IvanTopolcic** [comment]
So I've confirmed that you should not need to add the repository_url to your function. It should just work with the commit sha. I think we could perhaps make the documentation more clear here that it's not required for the serverless use case.

**Comment by mccorkle** [comment]
When I go to Integrations -> Link Source Code via the Datadog web app, it still demands "git.repository_url" be tagged on my telemetry -- blocking my ability to complete the APM setup:

![Screen Shot 2022-12-12 at 7 47 43 PM](https://user-images.githubusercontent.com/2091058/207199166-7292bc41-df65-4e47-8082-d4951cfe1cd4.png)

**Comment by annerajb** [comment]
I found this same page today and was wondering what was up with this. @IvanTopolcic 

can we reopen this?
