### ISSUE TITLE
plugin duplicates all entry files

### ISSUE THREAD

**Issue by dncrews** [DataDog/serverless-plugin-datadog#31]
**Background**

Because of the way that the DataDog plugin wraps the functions, all of the files are duplicated. Today, this caused my Lambda size to become 3 times the original size. This is especially a problem with serverless-webpack, as each file becomes much larger than usual.

**Repository showing issue**
https://github.com/dncrews/datadog-serverless-bug#issue-2-multiple-uses-of-a-handler-file-multiplies-the-filesize

**Expected Behavior**

the file should be re-used.

**Actual Behavior**

the file is replicated for each different function.

## Specifications

  - Serverless Framework version: 1.65.0
  - Datadog Serverless Plugin version: 0.16.0
  - Lambda function runtime: nodejs10.x
  - Serverless Webpack version: 5.2.0

## Workaround

The current workaround is to deploy the serverless functions "individually". Unfortunately, this also causes the build to take incrementally longer for each webpack build that it has to perform.

```yml
# serverless.yml
package:
  individually: true
```

**Comment by DarcyRaynerDD** [comment]
👋 Hi @dncrews, thanks for the report. Just so I understand, at the moment we create a new wrapper file for each handler. So if you have written 3 handlers in one file, that will produce 3 wrapper files, which means 3 bundles are generated. So the solution would be for us to create one wrapper file per source file that contains handlers?

**Comment by dncrews** [comment]
Hey @DarcyRaynerDD that's correct. If there were a single wrapper file per handler-file, this issue would be resolved.

**Comment by DarcyRaynerDD** [comment]
Hi @dncrews , just an update. I've added this as work to our internal board. We'll update here with any progress.

**Comment by DarcyRaynerDD** [comment]
@dncrews, sorry for the wait. We've updated the plugin with a fix for this issue. Can you confirm whether this works for you?

**Comment by tianchu** [comment]
Hi @dncrews I'm closing the issue assuming the problem has been fixed, but feel free to reopen if that's not the case.

**Comment by dncrews** [comment]
Thank you. We did finally have a release with this code, and performance improved significantly. I haven’t been able to verify the file results, but I’ll let you know if it’s still an issue.
