### ISSUE TITLE
Don't require the `DATADOG_API_KEY` and `DATADOG_APP_KEY` environment variables when `integrationTesting` is true

### ISSUE THREAD

**Issue by dls314** [DataDog/serverless-plugin-datadog#310]
## Expected Behavior
When `integrationTesting` is true, the `serveless package` command will complete, even if the the `DATADOG_API_KEY` and `DATADOG_APP_KEY` environment variables aren't available.

## Actual Behavior

Error: When `monitors` is enabled, `DATADOG_API_KEY` and `DATADOG_APP_KEY` environment variables must be set.

## Steps to Reproduce the Problem

  1. Configure a `monitors` property of the `custom.datadog` property in serverless.yml
  1. Set `custom.datadog.integrationTesting` to true
  1. Run `serverless package`

## Specifications

  - Serverless Framework version: ^3.23.0
  - Datadog Serverless Plugin version: ^5.9.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs16.x
  
## Stacktrace
  
  ```
: Error:
: Error: When `monitors` is enabled, `DATADOG_API_KEY` and `DATADOG_APP_KEY` environment variables must be set.
:     at validateConfiguration (\node_modules\serverless-plugin-datadog\src\index.ts:475:13)
:     at ServerlessPlugin.<anonymous> (\node_modules\serverless-plugin-datadog\src\index.ts:110:5)
:     at Generator.next (<anonymous>)
:     at \node_modules\serverless-plugin-datadog\dist\src\index.js:34:71
:     at new Promise (<anonymous>)
:     at __awaiter (\node_modules\serverless-plugin-datadog\dist\src\index.js:30:12)
:     at ServerlessPlugin.beforePackageFunction (\node_modules\serverless-plugin-datadog\dist\src\index.js:98:16)
:     at PluginManager.runHooks (\node_modules\serverless\lib\classes\plugin-manager.js:530:15)
:     at PluginManager.invoke (\node_modules\serverless\lib\classes\plugin-manager.js:565:20)
:     at async PluginManager.run (\node_modules\serverless\lib\classes\plugin-manager.js:604:7)
:     at async Serverless.run (\node_modules\serverless\lib\serverless.js:174:5)  
:     at async \node_modules\serverless\scripts\serverless.js:771:9
  ```

**Comment by sfirrin** [comment]
Hi @dls314 thanks a lot for opening this issue

We fixed the problem in February (see PR linked above) but I only just now realized that we forgot to notify you. This should be fixed and ready for you to use now. Thanks again and please let us know if you run into any other issue.
