### ISSUE TITLE
Error - no such file or directory - via serverless deploy action

### ISSUE THREAD

**Issue by ScopeSV** [DataDog/serverless-plugin-datadog#311]
## Expected Behavior
pushes build correctly through serverless github actions

## Actual Behavior
When serverless action is about to push to AWS, it crashes. 
```
Error: ENOENT: no such file or directory, stat '/github/workspace/node_modules/cpu-features/build/node_gyp_bins/python3'
```
## Steps to Reproduce the Problem
When I add 
```
"serverless-plugin-datadog": "^5.9.0"
```
To my `package.json` it crashes. If I remove it, the build is published correctly.
This is regardless if I'm adding `serverless-plugin-datadog` to my `serverless.yml` or not.

**If I deploy with `serverless-plugin-datadog` directly from my terminal, it succeeds.**

serverless github action is used straight out of the box:
```
      - name: Deploy serverless
        uses: serverless/github-action@v3
        with:
          args: deploy --stage pre-prod
```

## Specifications

  - Serverless Framework version: 
Framework Core: 3.23.0
Plugin: 6.2.2
SDK: 4.3.2

  - Datadog Serverless Plugin version:  5.9.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): 
  
## Stacktrace
  
```
Error:
Error: ENOENT: no such file or directory, stat '/github/workspace/node_modules/cpu-features/build/node_gyp_bins/python3'
    at Object.statSync (fs.js:1132:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/graceful-fs/polyfills.js:319:16)
    at Object.statSync (/github/workspace/node_modules/graceful-fs/polyfills.js:319:16)
at checkPaths (/github/workspace/node_modules/serverless-plugin-typescript/node_modules/fs-extra/lib/copy-sync/copy-sync.js:183:31)
    at copyDirItem (/github/workspace/node_modules/serverless-plugin-typescript/node_modules/fs-extra/lib/copy-sync/copy-sync.js:117:20)
    at /github/workspace/node_modules/serverless-plugin-typescript/node_modules/fs-extra/lib/copy-sync/copy-sync.js:111:39
    at Array.forEach (<anonymous>)
    at copyDir (/github/workspace/node_modules/serverless-plugin-typescript/node_modules/fs-extra/lib/copy-sync/copy-sync.js:111:23)
   ++ more stack trace
```

**Comment by astuyve** [comment]
Hi, your stack trace doesn't call through this library at all; so I don't think this issue belongs here.

However I suspect I can still help:

Serverless plugins are simply node modules. When I read the code for the Serverless github action, it doesn't actually run `serverless plugin install -n serverless-plugin-datadog`, or `npm install` in the working directory. [source](https://github.com/serverless/github-action/blob/master/Dockerfile).

Given that this works on your machine but not in CI, I suggest you open an issue in [the action repository](https://github.com/serverless/github-action/) to report this, and build your own github action instead.

Thanks!
