### ISSUE TITLE
How to filter requests on trace

### ISSUE THREAD

**Issue by alejandrombc** [DataDog/serverless-plugin-datadog#317]
This is not a bug but rather a question, how can I filter some requests inside traces?.

I make some dynamo queries with sensitive data that would like to avoid logging, Is there a way to filter some outputs of requests inside traces (APM)?

Sorry if this is on the documentation, but I could'nt find it

**Comment by Danny-Driscoll** [comment]
Hey, yes there are options for filtering out data within traces. Our configuration options for filtering APM data in Lambda functions are documented here: https://docs.datadoghq.com/serverless/configuration?tab=datadogcli#filter-or-scrub-sensitive-information-from-traces

**Comment by sfirrin** [comment]
Hi @alejandrombc I'm going to close this out as part of cleaning up our open issues. If you're still having any problem please feel free to reopen this
