### ISSUE TITLE
Plugin doesn't create policy for the DD_FETCH_LAMBDA_TAGS

### ISSUE THREAD

**Issue by asaghri** [DataDog/serverless-plugin-datadog#32]
## Expected Behavior

Since the release **aws-dd-forwarder-3.2.0** of the lambda forwarder, it's possible to get the lambda function tags. 

However, in order to do this you need to add the **tag:GetResources** permission to the the lambda functions.

See the datadog documentation here : [https://docs.datadoghq.com/integrations/amazon_lambda/?tab=awsconsole#enabling-enhanced-real-time-lambda-metrics](https://docs.datadoghq.com/integrations/amazon_lambda/?tab=awsconsole#enabling-enhanced-real-time-lambda-metrics)

So the expected behaviour would be to automatically add this permission to all the lambda if the we choose the DD_FETCH_LAMBDA_TAGS

## Actual Behavior

The permission is not added, and the lambda forwarder cannot get the lambda functions tags in the logs

## Steps to Reproduce the Problem

  1. Have the lambda forwarder with DD_FETCH_LAMBDA_TAGS set to true
  2. Use this plugin for logs
  3. Check you function logs in datadog, the tags are missing

## Specifications

  - Serverless Framework version: 1.60.1
  - Datadog Serverless Plugin version: latest
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 10

**Comment by DarcyRaynerDD** [comment]
Hi @asaghri ,
Thanks for the feature request, we agree that this would be useful. I'm adding this as a ticket to our internal work tracking tools. I'll post any updates here as we progress.

**Comment by DarcyRaynerDD** [comment]
Okay, so we just looked into this. The bullet point about tag:GetResource was a mistake in our docs. You don't need to add permissions to the lambda function being monitored itself, just the log forwarder. In the cloud formation template we provide, we add those permissions for you. Sorry for the confusion and inconvenience, we are working to get those docs corrected.

**Comment by DarcyRaynerDD** [comment]
We've updated our docs with a fix for that mistake. I'm going to close this issue. Thanks for the feedback.
