### ISSUE TITLE
Depencency on a vulnerable version of simple-git

### ISSUE THREAD

**Issue by trygve-aaberge-adsk** [DataDog/serverless-plugin-datadog#325]
The latest version of serverless-plugin-datadog (5.13.0) transitively depends on a vulnerable version of simple-git via the dependency on @datadog/datadog-ci 1.13.3.

See here for details about the vulnerability: https://github.com/advisories/GHSA-9p95-fxvg-qgq2

Could you please update it?

**Comment by sfirrin** [comment]
Hi @trygve-aaberge-adsk, thanks for opening this issue

I've just merged the PR linked above to update our datadog-ci version and released the change in https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.14.1

**Comment by trygve-aaberge-adsk** [comment]
Thanks!
