### ISSUE TITLE
Changes v5.0.1 to v5.1.0 onwards -  Runtime.ImportModuleError  Error: Cannot find module 'handler'

### ISSUE THREAD

**Issue by 7jpsan** [DataDog/serverless-plugin-datadog#328]
## Expected Behavior

The Handler property of a CF resource `"Type": "AWS::Lambda::Function"` is preserved

## Actual Behavior

When building the lambdas (we are using typescript + esbuild) up until v5.0.1 will generate the correct CF Template, from 5.1.0 onwards all the lambdas triggered by http events will have their Handler property updated from the actual place: index.handler to something like: 

`/node_modules/datadog-lambda-js/handler.handler`

Actual error when running the lambda in the cloud: 

```
Endpoint response body before transformations: {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/index.mjs","trace":["Runtime.ImportModuleError: Error: Cannot find module 'handler'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)","    at async start (file:///var/runtime/index.mjs:1200:23)","    at async file:///var/runtime/index.mjs:1206:1"]}
Thu Dec 15 16:17:17 UTC 2022 : Lambda execution failed with status 200 due to customer function error: Error: Cannot find module 'handler'
```

## Steps to Reproduce the Problem

  1. latest serverless 3.x
  2. Install 5.0.1 (or up to latest at the time of reporting)
  1. build a lambda with typescript and the plugin configured to add a forwarder (not layer, not extension)
  1. inspect the generated `.serverless/cloudformation.update.json` generated file. Note how the Handler property points to datadog now.

## Specifications

  - Serverless Framework version: 3.25.1
  - Datadog Serverless Plugin version:  5.1.0 (onwards)
  - Lambda function runtime: node16
  - "esbuild": "^0.15.16",
  
## Stacktrace
  
  None, it deploys, but it mutates the CF in strange ways!

**Comment by astuyve** [comment]
Hi, can you share the `datadog` configuration block of your `serverless.yml` config file, as well as the `package.json` file (specifically `datadog-lambda-js` and `dd-trace` versions)?
Please redact any sensitive information like secrets or API keys.
Thanks!

**Comment by 7jpsan** [comment]
>
> Additionally - can you help me understand what you're trying to achieve? If you're not using `datadog-lambda-js` as a layer, and not bundling it yourself, then I'm unsure why you are using this library. That's effectively what it's intended to provide, an integration for our instrumentation with the Serverless Framework.
> 

To clarify, the intention is to "eventually" use it as a layer, but for a reason outside my control, we cannot do that just yet (need to get the apiKey from some CF output first). SO we have opted to use a forwarder

One of the options you have  (according to the documentation) is the ability to set a forwarder (another lambda that knows the apiKey, has the datadog dep and is accessible) so CW subscribes the logs to it and it will eventually appear on our datadog. 

>
> Hi, can you share the datadog configuration block of your serverless.yml
>

There is no dependency called `datadog-lambda-js` i'm afraid...

```
datadog:
  site: datadoghq.com
  addLayers: false # One of: Layer / Extension / Forwarder (last one is the current setup.)
  logLevel: 'info'
  enableXrayTracing: false
  enableDDTracing: false
  forwarder: 'arn:aws:lambda:${aws:region}:${aws:accountId}:function:datadog-forwarder'
  enableTags: false
  addExtension: false
  enableSourceCodeIntegration: false
```

**Comment by astuyve** [comment]
Hi @7jpsan thanks for that clarification. Unfortunately I think there is a misunderstanding here.

This library is not intended to function without `datadog-lambda-[js/py/etc]` being present. This is done via either Layers or specifying the runtime library as a dependency. The fact that handler redirection wasn't always performed prior to 5.1 is a bug.

When you set `addLayers` to `false`, you see the following message:
<img width="589" alt="Skipping adding Lambda Library Layers, make sure you are adding them yourself" src="https://user-images.githubusercontent.com/1598537/208120229-b12f7c95-1ba4-4cc0-9304-8eb793c65c48.png">.

From what I can see, your setup will only forward logs to Datadog. You won't get APM/Tracing, enhanced metrics, profiling, etc.

If that's your intention, this library is not currently suitable for this task. Instead, we offer even simpler integration methods with no additional dependencies. You can simply use the Datadog app to forward some or all Lambda logs. No need to change your application.

Instructions are in the [documentation](https://docs.datadoghq.com/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function/?tab=awsconsole).

Please let me know if you have any additional questions.
Thanks!

**Comment by astuyve** [comment]
Closing as we haven't heard back here. Please let me know if this comment helps @7jpsan, thanks!
