### ISSUE TITLE
APM setup requires git.repository_url but 

### ISSUE THREAD

**Issue by annerajb** [DataDog/serverless-plugin-datadog#332]
## Expected Behavior
the serverless plugin adds the git.repository_url and the git.commit.sha

## Actual Behavior
it does not it just adds the git.commit.sha

Read the previous report for this issue on #309 

it was closed before a whole new page that is blocking APM setup shows up asking for the field to be added to finish the setup.

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/882782/210885188-b7f3b533-8d48-498c-9d09-f97cc805651c.png">

**Comment by sfirrin** [comment]
Hi @annerajb thanks for opening this issue

We previously removed this tag because it was causing an unrelated issue but that is now resolved so we are going to be adding it back to get this working how it should

**Comment by annerajb** [comment]
@sfirrin 

Any update was this released?
can you link the release it went out?

**Comment by thedavl** [comment]
Hi @annerajb, we've merged the changes to add the git.repository_url along with the commit sha. We'll cut a new release shortly, and I'll link it here.

**Comment by thedavl** [comment]
@annerajb [new release of the plugin is out](https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.17.0). Let me know if you have any questions or further issues!
