### ISSUE TITLE
Runtime.ImportModuleError: Error: Cannot find module '@node-rs/xxhash-linux-arm64-gnu'

### ISSUE THREAD

**Issue by theonetheycallneo** [DataDog/serverless-plugin-datadog#346]
## Expected Behavior
serverless-plugin-datadog should deploy lambdas successfully

## Actual Behavior
serverless-plguin-datadog deploys but runtime throws error

## Steps to Reproduce the Problem

  1. serverless-plugin-datadog
  1.
  1.

## Specifications

  - Serverless Framework version: 
  
  "serverless": "3.25.1",
  
  - Datadog Serverless Plugin version: 
  
  "serverless-plugin-datadog": "5.17.0",
  
  - Lambda function runtime (Python 3.7, Node 10, etc.): 
  
  runtime: 'nodejs16.x',
  
## Stacktrace
  
  ```

{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '@node-rs/xxhash-linux-arm64-gnu'\nRequire stack:\n- /var/task/node_modules/@node-rs/xxhash/index.js\n- /var/task/node_modules/@nestjs/core/inspector/deterministic-uuid-registry.js\n- /var/task/node_modules/@nestjs/core/inspector/uuid-factory.js\n- /var/task/node_modules/@nestjs/core/injector/instance-wrapper.js\n- /var/task/node_modules/@nestjs/core/injector/injector.js\n- /var/task/node_modules/@nestjs/core/injector/module-ref.js\n- /var/task/node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js\n- /var/task/node_modules/@nestjs/core/inspector/serialized-graph.js\n- /var/task/node_modules/@nestjs/core/injector/container.js\n- /var/task/node_modules/@nestjs/core/injector/index.js\n- /var/task/node_modules/@nestjs/core/index.js\n- /var/task/src/main-lambda-entrypoint.js\n- /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js\n- /opt/nodejs/node_modules/datadog-lambda-js/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module '@node-rs/xxhash-linux-arm64-gnu'","Require stack:","- /var/task/node_modules/@node-rs/xxhash/index.js","- /var/task/node_modules/@nestjs/core/inspector/deterministic-uuid-registry.js","- /var/task/node_modules/@nestjs/core/inspector/uuid-factory.js","- /var/task/node_modules/@nestjs/core/injector/instance-wrapper.js","- /var/task/node_modules/@nestjs/core/injector/injector.js","- /var/task/node_modules/@nestjs/core/injector/module-ref.js","- /var/task/node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js","- /var/task/node_modules/@nestjs/core/inspector/serialized-graph.js","- /var/task/node_modules/@nestjs/core/injector/container.js","- /var/task/node_modules/@nestjs/core/injector/index.js","- /var/task/node_modules/@nestjs/core/index.js","- /var/task/src/main-lambda-entrypoint.js","- /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js","- /opt/nodejs/node_modules/datadog-lambda-js/runtime/index.js","    at ImportModuleError.ExtendedError [as constructor] (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:113:28)","    at new ImportModuleError (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:123:42)","    at /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:273:31","    at step (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:43:23)","    at Object.throw (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:24:53)","    at rejected (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:16:65)"]}
EXTENSION       Name: datadog-agent     State: Ready    Events: [INVOKE,SHUTDOWN]
  ```

**Comment by astuyve** [comment]
Hi @theonetheycallneo, thanks for reaching out!

I took a look at your stack trace and this seems to be caused by something unrelated to this library.

The error bubbles through `UserFunction` because `require` or `import` your handler code. Doing so throws this error:

>{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '@node-rs/xxhash-linux-arm64-gnu'\nRequire stack:\n- /var/task/node_modules/@node-rs/xxhash/index.js\n- /var/task/node_modules/@nestjs/core/inspector/deterministic-uuid-registry.js\n- /var/task/node_modules/@nestjs/core/inspector/uuid-factory.js\n- /var/task/node_modules/@nestjs/core/injector/instance-wrapper.js\n- /var/task/node_modules/@nestjs/core/injector/injector.js\n- /var/task/node_modules/@nestjs/core/injector/module-ref.js\n- /var/task/node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js\n- /var/task/node_modules/@nestjs/core/inspector/serialized-graph.js\n- /var/task/node_modules/@nestjs/core/injector/container.js\n- /var/task/node_modules/@nestjs/core/injector/index.js\n- /var/task/node_modules/@nestjs/core/index.js\n- /var/task/src/main-lambda-entrypoint.js\n- /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js\n- /opt/nodejs/node_modules/datadog-lambda-js/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module '@node-rs/xxhash-linux-arm64-gnu'","Require stack:","- /var/task/node_modules/@node-rs/xxhash/index.js","- /var/task/node_modules/@nestjs/core/inspector/deterministic-uuid-registry.js","- /var/task/node_modules/@nestjs/core/inspector/uuid-factory.js","- /var/task/node_modules/@nestjs/core/injector/instance-wrapper.js","- /var/task/node_modules/@nestjs/core/injector/injector.js","- /var/task/node_modules/@nestjs/core/injector/module-ref.js","- /var/task/node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js","- /var/task/node_modules/@nestjs/core/inspector/serialized-graph.js","- /var/task/node_modules/@nestjs/core/injector/container.js","- /var/task/node_modules/@nestjs/core/injector/index.js","- /var/task/node_modules/@nestjs/core/index.js","- /var/task/src/main-lambda-entrypoint.js","- /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js","- /opt/nodejs/node_modules/datadog-lambda-js/runtime/index.js","    at ImportModuleError.ExtendedError [as constructor] (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:113:28)","    at new ImportModuleError (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:123:42)","    at /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:273:31","    at step (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:43:23)","    at Object.throw (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:24:53)","    at rejected (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:16:65)"]}


Does removing `serverless-plugin-datadog` resolve this issue? If so, can you provide a minimal reproducible example so we can test?

Thanks!

**Comment by astuyve** [comment]
Closing this as there's been no response for some time. Feel free to re-open if you're still experiencing this issue, and can attach an example.

Thank you!
