### ISSUE TITLE
Serverless Peer Dependency locks to version 3.27

### ISSUE THREAD

**Issue by lvanoort** [DataDog/serverless-plugin-datadog#349]
[This change](https://github.com/DataDog/serverless-plugin-datadog/pull/344) introduces a peer dependency on a specific version of Serverless Framework, which is troublesome for consumers of this plugin who are not using that version of Serverless Framework.

It would be appreciated if this could be either reverted or the version string changed to something like `2.x || 3.x` to allow a broader range of peer versions of Serverless (including 2.x because unless there's something in this plugin that is not 2.x compatible, it's still very widely [used](https://www.npmjs.com/package/serverless?activeTab=versions)).

**Comment by astuyve** [comment]
Hi @lvanoort -

Thanks for reaching out! The intention of this change was to avoid users inadvertently packaging the serverless framework as a dependency when installing this library, and as preparation for the EOL of 2.x and allow us to take advantage of features in 3.x (specifically the CLI experience).

That said, this library is compatible with 2.x at present, so we can broaden the peer dependency range to allow for this, then we can explore other ways to handle popular versions effectively.

Thanks!
AJ

**Comment by astuyve** [comment]
This is fixed in 5.18.0
