### ISSUE TITLE
Unable to upgrade from v5.16.0 to v5.17.0

### ISSUE THREAD

**Issue by jprice-da15252** [DataDog/serverless-plugin-datadog#355]
## Expected Behavior
Upgrading serverless-plugin-datadog from v5.16.0 to v5.17.0 and redeploying should upgrade the deployed serverless plugin to the newer version. 
https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.17.0

Snippet of serverless service's package.json `devDependencies`:

```"serverless-plugin-datadog": "5.17.0"```

## Actual Behavior
![image](https://user-images.githubusercontent.com/2137788/219100305-c95860fa-b43e-483a-86dc-b252644236aa.png)

## Steps to Reproduce the Problem

  1. Deploy serverless service with serverless-plugin-datadog v5.16.0 specified as devDependency (also reproducible as a regular dependency (non-dev)
  1. Upgrade serverless-plugin-datadog to 5.17.0 using your package manager
  1. Serverless deploy with `--force`. Issue is reproducible with serverless `deploymentMethod` set as either `changesets` or `direct`
  1. Observe `dd_sls_plugin: v5.16.0` version in the DataDog UI's trace details

Worth noting is that there doesn't seem to be any updates to the us-east-1 layer versions between v5.16.0 and v5.17.0:
https://github.com/DataDog/serverless-plugin-datadog/blob/master/src/layers.json#L306 . I don't fully understand the implications of this; it is just an observation and the README only mentions this file briefly. 

Also worth noting. I have a separate environment which does show version 5.17.0 installed in the DataDog UI's trace details. I attribute this to having a carat version specified at deployment time, which was coincidentally the first time the environment had been deployed to with my changes to add the DataDog serverless plugin. 

## Specifications

  - Serverless Framework version: 3.27.0
  - Datadog Serverless Plugin version: 5.17.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14
  
## Stacktrace  
N/A

## Additional Context
The affected environment is one in which I am using to configure source code linking. With version 5.16.0, only a git sha1 sum is added, and that is an incorrect checksum. If I specify my own sha1 and repo URL with the plugin's `tags` directive, those are appended to DD_TAGS, causing it to be formatted like so:
```
"git.commit.sha:<GIT_COMMIT_SHA>,git.repository_url:<git-provider.example/me/my-repo>,git.commit.sha:<GIT_COMMIT_SHA>,git.repository_url:<git-provider.example/me/my-repo>"
```
Despite the above, the checksum shown in the DataDog UI is still an incorrect one. I assume the incorrect one is coming from GitHub metadata. 

Lambda Env Var (repository redacted): 
![image](https://user-images.githubusercontent.com/2137788/219115754-adb4d511-306f-4edd-9be4-b76c363675f4.png)
DataDog APM Trace details:
![image](https://user-images.githubusercontent.com/2137788/219115956-e45569e7-124f-43b8-92df-3abcc7601e95.png)
_Note:_ vars with the `GIT_` prefix are populated by serverless-plugin-git-variables and are the accurate values. 

I am hoping 5.17.0's inclusion of #334 allows me to complete configuration, but I can't seem to upgrade to it for the reasons outlined in the above. If I should open a separate issue for these additional observations, I'm happy to do so.

**Comment by jprice-da15252** [comment]
Corrected inverted versions in the title and description to avoid confusion

**Comment by duncanista** [comment]
Hello @jprice-da15252 !

Thanks for opening this issue,

These tags are updated asynchronously from APM traces. So this process can take some time. Nonetheless, if you're experiencing a longer than expected (few minutes) delay, the best way we can help is for you to file a support ticket so we can follow up with your account directly 🙏🏽 

I'd suggest you to upgrade, and check new invocations after some time to verify the tagging is correct. 

After that, let me know if #334 allows you to complete the configuration issue. If it doesn't, please open another issue for that specifically if possible.

– Closing the issue, but feel free to re-open at any time!

**Comment by jprice-da15252** [comment]
Thanks for the response and clarification. The primary issue that I am experiencing was that even though I tried to upgrade, the plugin didn't seem to actually upgrade, even hours after upgrading the dependency and pushing changes. Since one environment of ours did have v5.17 installed with it, just as its initial version, there seems to be an issue with upgrades specifically if the service was first deployed with 5.16.0 defined as the dependency version. 

This is my change to use v5.18.0, which hit our `main` branch 48 minutes ago and was auto-deployed to the environment I am testing in:
![image](https://user-images.githubusercontent.com/2137788/220414469-b2a95d10-fb2c-4e2e-a693-3a330ab0ca7b.png)

Traces from the same environment as of 15 minutes ago:
![image](https://user-images.githubusercontent.com/2137788/220414837-c4514cb1-8c3d-4582-99b8-6287ffb8bdc2.png)

I don't know if this is related, though it would be nice to confirm or rule out for my own education, but the lambda layer versions were last updated for NodeJS in 59c33bb. This change made it into v5.16.0, but hasn't changed since:
![image](https://user-images.githubusercontent.com/2137788/220415387-a5b840e7-e626-4ac2-a0b0-12b6d6b54e0f.png)

**Comment by astuyve** [comment]
Hi @jprice-da15252,

Thanks for reaching out! Can you verify a couple of things for us?
- Check the `layers` section of your Lambda function in the AWS console and verify the layer versions are correct? For 5.17.0 we'd expect to see Extension version 37 and Node 14.x version 86. Layer versions don't always increase with every version of the plugin (some releases, like 5.17.0, only modify this library).
- Verify that any `tags` in the AWS console reflect the version tag 5.17.0

You also may try going straight to 5.18.0 and verifying the node layer upgrades to version 87.

If you see that the layer has been upgraded but the APM span tags still reflect an older version within Datadog, I think the best path forward would be to open a support ticket so myself or another engineer can look into your specific account and identify any possible conflicting issues here.

Thanks again!

**Comment by jprice-da15252** [comment]
Good to know about the Lambda layer version not always being updated. The extension and layer versions do match their expected respective versions:
![image](https://user-images.githubusercontent.com/2137788/220748867-5e9466a2-38fe-4d46-acc9-bec9c5d9868c.png)

The Lambda tags also indicate that the `dd_sls_plugin` version is as it should be:
![image](https://user-images.githubusercontent.com/2137788/220748942-46999594-f9aa-4fd7-808b-50499fe72fc9.png)

So this does appear to be an issue with the traces. Now that I know that the new version is actually in use, I will experiment with setting `uploadGitMetadata` to false and configuring serverless to provide the github-related  DD tags.

I do have a support ticket that I opened today: https://help.datadoghq.com/hc/en-us/requests/1109549
