### ISSUE TITLE
Allow disabling function handler wrapping

### ISSUE THREAD

**Issue by camero2734** [DataDog/serverless-plugin-datadog#363]
## Expected Behavior
Since we already have a `node_modules` lambda layer we opted out of `addLayers`, since our deployed code will already have access to `datadog-plugin-js` and `dd-trace`. However, we would also like to be able to opt out of the function wrapping/indirection completely and just wrap the lambda handler manually according to https://docs.datadoghq.com/serverless/guide/handler_wrapper/

## Actual Behavior
It would be great if there was an option to disable the `redirectHandlers` method call seen here: https://github.com/DataDog/serverless-plugin-datadog/blob/a4783444b9b2c604ae90ae68b99c08c2d584ed73/src/index.ts#L281

We're currently using `patch-package` to just comment out this line in our project, but adding a simple config option (something like `redirectHandlers: false`) to skip this statement would be great.

## Specifications

  - Serverless Framework version: 3.28.1
  - Datadog Serverless Plugin version: 5.20.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 18

**Comment by tianchu** [comment]
I think https://github.com/DataDog/serverless-plugin-datadog/pull/149 could help.

**Comment by camero2734** [comment]
I believe that that only allows modifying `config.customHandler`; we would like to skip the `redirectHandlers` altogether

**Comment by tianchu** [comment]
Sorry for the late reply @camero2734. I see the problem now, but I don't think we have a good solution here. I know you **can** wrap the handler in the function code, but you don't have to, right? We created this doc https://docs.datadoghq.com/serverless/guide/handler_wrapper/ specifically for certain scenarios where the redirectHandlers break the instrumentation. I guess my question is that what is the advantage of manually applying the wrapper in code vs relying on the plugin to redirect the handler? Besides, the two main jobs the plugin has are 1. add layers 2. redirect handler, if you don't need either of them, perhaps you don't even need the plugin?
