### ISSUE TITLE
Debug Logging Sampling Rate

### ISSUE THREAD

**Issue by eclecticjohny** [DataDog/serverless-plugin-datadog#385]
Don't believe the other fields were relevant so just left expected behavior. 

## Expected Behavior

When using the serverless-plugin-datadog it would be nice instead of only having an option to turn off/on debug logging to have a debug sampling rate option so that debug logs can be captured automatically in production at a given rate. When using a supported logger (Winston/Pino) this setting would be respected.

**Comment by eclecticjohny** [comment]
Okay, thanks for the reply!

**Comment by sfirrin** [comment]
@eclecticjohny to follow up, it didn't cross my mind initially but we do support setting a percentage to retain logs matching a pattern at ingestion with https://docs.datadoghq.com/logs/guide/getting-started-lwl/#3-create-a-log-pattern-exclusion-filter
