### ISSUE TITLE
Support for configuring OTLP collectors

### ISSUE THREAD

**Issue by anthonyangel** [DataDog/serverless-plugin-datadog#402]
## Expected Behavior
I can configure the OTLP endpoints in the extension through parameters under `custom`

## Actual Behavior
I can not, however I can add `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT` and `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT` as env vars

**Comment by sfirrin** [comment]
Hi @anthonyangel thanks for opening this, it sounds like a good improvement. We will work on a PR and update you here

**Comment by duncanista** [comment]
🐸 Hey, @anthonyangel,

Sorry we haven't provided you with a response or a PR around this!
Lately, we have been swarmed with feature requests and ongoing work. For us to better triage this issue, [creating a support ticket in our platform](https://help.datadoghq.com/hc/en-us/requests/new) would help us a lot! Make sure to mark the product as `Infrastructure` and set the category to `Feature request`. You can also mention this GitHub issue. This will directly send it to our engineering team to better prioritization. 

I'll have to close this issue as part of this new process for feature requests!
If you have any concerns or questions, feel free to re-open the issue! 🙇🏽
