### ISSUE TITLE
Application crash when using serverless-plugin-datadog and stream as query (pg + pg-query-stream)

### ISSUE THREAD

**Issue by GuilhermeFernandes01** [DataDog/serverless-plugin-datadog#403]
## Expected Behavior
serverless-plugin-datadog should be able to handle query as stream.
It worked when I removed the serverless-plugin-datadog plugin from the project:
![image](https://github.com/DataDog/serverless-plugin-datadog/assets/26780625/40ca08e4-5810-4015-8cf3-4de434f3f100)
![image](https://github.com/DataDog/serverless-plugin-datadog/assets/26780625/e69e0fcf-38c9-4904-87c7-90bf055ec05d)

## Actual Behavior
serverless-plugin-datadog throws `Error: A query must have either text or a name. Supplying neither is unsupported.` I've seen a similar discussion about it [here](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/991).
![image](https://github.com/DataDog/serverless-plugin-datadog/assets/26780625/883fe842-8c04-4125-a69c-c4adcea46221)
![image](https://github.com/DataDog/serverless-plugin-datadog/assets/26780625/85cb5f00-8826-454a-938e-d58f299a938c)
![image](https://github.com/DataDog/serverless-plugin-datadog/assets/26780625/d7c69c08-3689-4265-9caa-0a6929911fd7)

## Steps to Reproduce the Problem

  1. Create serverless project
  2. Install the dependencies
 ```
npm install pg@8.11.0 pg-query-stream@4.5.0
npm install serverless-plugin-datadog@5.35.0 -D
```
  3. Configure your project
 Example of serverless.yml:
```yml
service: my-test
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}

functions:
  test:
    handler: index.test

plugins:
  - serverless-plugin-datadog

package:
  excludeDevDependencies: true
  patterns:
    - "node_modules/**"
    - "index.js"
    - "package*.json"
```
Handler example (index.js):
```js
const { PassThrough, Transform } = require('node:stream')
const { pipeline } = require('node:stream/promises')
const { Client } = require('pg')
const QueryStream = require('pg-query-stream')

exports.test = async function (event) {
  const pgClient = new Client({
    user: 'user',
    host: 'host',
    database: 'database',
    password: 'password',
    port: 'port'
  });

  await pgClient.connect();

  const query = 'SELECT * FROM "Table" LIMIT 10';
  const queryStream = new QueryStream(query);
  const stream = pgClient.query(queryStream);

  const transform = new Transform({
    objectMode: true,
    transform (chunk, encoding, callback) {
      callback(null, Buffer.from(JSON.stringify(chunk) + '\n'));
    }
  });

  const ndjsonStream = new PassThrough();

  await pipeline(stream, transform, ndjsonStream);

  // using my ndjsonStream to upload a file to a S3 bucket

  await pgClient.end();

  return {
    headers: {},
    statusCode: 200,
    body: JSON.stringify({ message: 'Success' }),
    isBase64Encoded: false
  };
};
```
4. Call the lambda function in AWS

## Specifications

  - Serverless Framework version: 3.32.2
  - Datadog Serverless Plugin version: 5.15.0, 5.34.0, 5.35.0 (I tested using these three versions)
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 18
  - pg version: 8.11.0
  - pg-query-stream version: 4.5.0
  
## Stacktrace
```
Error: A query must have either text or a name. Supplying neither is unsupported.
at Query.submit (/var/task/node_modules/pg/lib/query.js:152:14)
at Client._pulseQueryQueue (/var/task/node_modules/pg/lib/client.js:486:45)
at Client.query (/var/task/node_modules/pg/lib/client.js:581:10)
at /var/task/node_modules/dd-trace/packages/datadog-instrumentations/src/pg.js:55:28
at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
at Client.query (/var/task/node_modules/dd-trace/packages/datadog-instrumentations/src/pg.js:39:26)
at Object.inAppCampaignsIngestion (/var/task/v1/adapters/inAppCampaignsIngestion/index.js:32:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by astuyve** [comment]
Hey @GuilhermeFernandes01 - thanks for reaching out. Does this error goes away if you disable datadog tracing? (`DD_TRACING_ENABLED=false`)

this stack trace doesn't actually touch this library, it goes through [dd-trace-js](https://github.com/DataDog/dd-trace-js). I will ask that team and see if we should route the ticket there.

Thanks!

**Comment by GuilhermeFernandes01** [comment]
> Hey @GuilhermeFernandes01 - thanks for reaching out. Does this error goes away if you disable datadog tracing? (`DD_TRACING_ENABLED=false`)
> 
> this stack trace doesn't actually touch this library, it goes through [dd-trace-js](https://github.com/DataDog/dd-trace-js). I will ask that team and see if we should route the ticket there.
> 
> Thanks!

Hi @astuyve, thanks for answering.

Yes, the error gone away when I disabled datadog tracing using `DD_TRACING_ENABLED=false` as environment variable.

Let me know if I can help with more information.

**Comment by astuyve** [comment]
Hi, there's been no update here for many months and I haven't seen a ticket or support case, so I must assume something has either solved this for you or another change fixed this in dd-trace-js (as documented above).

Either way this library only applies that telemetry, so if this is still an issue I'd ask you to open a ticket in that repository.

Thank you!
