### ISSUE TITLE
Add support for multiple functions in serverless.yaml

### ISSUE THREAD

**Issue by karadikidd** [DataDog/serverless-plugin-datadog#414]
## Expected Behavior
Ability to set the `service` name per each function in the `serverless.yml` file

## Actual Behavior
All functions are utilizing the same DD_SERVICE environment variable. Consequently, some of the logs are being sent as `service_undefined`, while others are sent with the correct `service` name.

## Steps to Reproduce the Problem

  1. Create a `serverless.yml` with multiple functions
  2. Add a `custom` > `datadog` section as suggested in the [docs](https://docs.datadoghq.com/serverless/libraries_integrations/plugin/#configuration-parameters)
  3. Deploy

## Specifications

  - Serverless Framework version: 3
  - Datadog Serverless Plugin version: v5.38.1
  - Lambda function runtime (Python 3.7, Node 10, etc.): Python 3.10
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by DarcyRaynerDD** [comment]
Hi @karadikidd, have you tried setting DD_SERVICE in a "environment" block on each function? Does that resolve the issue for you?

**Comment by karadikidd** [comment]
> Hi @karadikidd, have you tried setting DD_SERVICE in a "environment" block on each function? Does that resolve the issue for you?

Hi @DarcyRaynerDD, I have indeed tried that... Unfortunately, it didn't resolve the issue.

**Comment by karadikidd** [comment]
FYI, we've broken the yaml into dedicated yaml files and are using serverless compose to deploy everything. This seems to resolve our problem, but in general it would be nice to have such support in the future.

**Comment by karadikidd** [comment]
It seems the issue was associated with a third-party logger we were using, which appended a `service` key to our JSON.
Sorry for the trouble, I will close this issue now.
