### ISSUE TITLE
When changing the Lambda architecture from x86 to arm64 , the dd_trace_dotnet layer is not modified to dd-trace-dotnet-ARM

### ISSUE THREAD

**Issue by ValeriyaIvanovaPolestar** [DataDog/serverless-plugin-datadog#419]
## Expected Behavior
After changing the lambda architecture in the serverless file from x86 to arm64, the datadog layers must be for the arm architecture, for example expected layers in that case for dotnet app and eu-north-1 region are: 
```
arn:aws:lambda:ap-south-1:464622532012:layer:Datadog-Extension-ARM:47 
arn:aws:lambda:ap-south-1:464622532012:layer:dd-trace-dotnet-ARM:9 
```
## Actual Behavior
In our case only the Datadog-Extension-ARM layer was updated and the dd-trace-dotnet layer stays the same as before. So after changing the architecture to arm64 we got : 
```
arn:aws:lambda:ap-south-1:464622532012:layer:Datadog-Extension-ARM:47 - as expected 
arn:aws:lambda:ap-south-1:464622532012:layer:dd-trace-dotnet:9 - same as before so not working properly. 

```
If we change manually the layer to the expected one (dd-trace-dotnet-ARM ) , everything works properly. 

## Steps to Reproduce the Problem

  1. Deploy dotnet app with serverless and specify the architecture to be x86
  2. Check the datadog layers to be the expected ones for x84 arch.
  3. Change the architecture to arm64
  4. Check the datadog layers were changed to  Datadog-Extension-ARM ( correct) and dd-trace-dotnet (wrong). 

## Specifications

  - Serverless Framework version: 3 
  - Datadog Serverless Plugin version: 5.42.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): dotnet6
  
## Stacktrace
  
No errors during deployment.

**Comment by astuyve** [comment]
Thanks for this report @ValeriyaIvanovaPolestar! I'll update this ticket when we're ready with a fix.

**Comment by sfirrin** [comment]
Hi @ValeriyaIvanovaPolestar, this should be fixed in the new release https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.48.0

Thanks for opening the issue and please let us know if you run into anything else
