### ISSUE TITLE
Downstream traces disappear when upgrading serverless-plugin-datadog

### ISSUE THREAD

**Issue by eclecticjohny** [DataDog/serverless-plugin-datadog#424]
## Expected Behavior
I have multiple services using serverless-plugin-datadog that have not been updated in a while. Some of these services call each other and the top level service will show the complete flame graph of the services called from the top level service. 

## Actual Behavior
When I try to update just serverless-plugin-datadog in my package.json in any of these services. It causes the downstream service to only show as a single span in the flame graph for the top level service. If I go to the downstream service, all the spans show for that call in the flame graph there. For instance, I have a downstream service that shows it's top-level span and all child spans in the calling service flame graph running on 5.9.0 of the plugin. When I update the downstream service to 5.44.0, the span and child spans show in the downstream service but not in the calling service flame graph. Updating this single package does seem to update a lot of packages in my package-lock.json.

## Steps to Reproduce the Problem

  1. Update current serverless-plugin-datadog in package.json to any newer version
  2. Npm install
  3. Deploy service and observe traces

## Specifications

  - Serverless Framework version: 3.28.1
  - Datadog Serverless Plugin version: 5.9.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs16.x
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by eclecticjohny** [comment]
Here's a visual representation after upgrading several downstream services but leaving one alone.

before upgrade:
<img width="807" alt="Screenshot 2023-09-09 at 16 08 48" src="https://github.com/DataDog/serverless-plugin-datadog/assets/25906874/45a00419-5a56-4db6-af9f-6a43c4766aa3">

after upgrade:
<img width="811" alt="Screenshot 2023-09-09 at 16 08 29" src="https://github.com/DataDog/serverless-plugin-datadog/assets/25906874/b70cfdd6-c877-46f9-91f3-ffafa3a80b88">

**Comment by DarcyRaynerDD** [comment]
Hi @eclecticjohny, how does the parent call the child service? Are you using any intermediate services, (like SQS, SNS, API Gateway etc)? Or is it a direct lambda invocation?

**Comment by eclecticjohny** [comment]
It's always an http call from the parent service to the child service via axios.

**Comment by astuyve** [comment]
Hie @eclecticjohny - Thanks for reaching out!

This should work out of the box, but I won't be able to help you debug in a public github issue because I can't see any of the span data in the screenshots and don't think you'd want to share that data publicly.

Could I ask you to open a support ticket, and mention this issue as well as ask them to route it to me internally? I believe that'll be the fastest way to solve this for you.

Thanks!

**Comment by astuyve** [comment]
Closing this as there has been no update for a few months.

Feel free to re-open if necessary!

Thanks!
