### ISSUE TITLE
Update pydantic to latest (resolve vulnerability) once it's available (unless it's possible to pin master?)

### ISSUE THREAD

**Issue by leslie-canva** [DataDog/serverless-plugin-datadog#425]
## Expected Behavior

The latest lambda layer `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:48` should be free from vulnerabilities where possible.

## Actual Behavior

According to Amazon Inspector `pydantic` version `1.10.8` is installed however pydantic is now at version `2.3.0`. It looks like the fix isn't yet released but it would be good to update / keep an eye on it so the upgrade is minor instead of jumping many versions. 

https://security.snyk.io/vuln/SNYK-PYTHON-PYDANTIC-5907722

## Steps to Reproduce the Problem

  1. Use the layer in a Lambda with Amazon Inspector enabled

## Specifications

  - Datadog Serverless Plugin version: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:48
  - Lambda function runtime (Python 3.7, Node 10, etc.): python 3.9

**Comment by purple4reina** [comment]
Hi @leslie-canva, are you able to give a bit more detail on where the `pydantic` dependency is located? The Datadog Lambda Extension is a golang binary, so doesn't even use python at all. I also checked the dependencies for our Python3.9 layer and also could not find `pydantic`.

**Comment by astuyve** [comment]
closing this as it is not a python project and there has been no update
