### ISSUE TITLE
Non syntax related 400 error

### ISSUE THREAD

**Issue by johnbuildsthings** [DataDog/serverless-plugin-datadog#435]
## Expected Behavior

During serverless deployment the datadog plugin should update / create monitors associated with the service.

## Actual Behavior

If the service has > 30 monitors not all will be collected in the list of existing monitors leading to 400 errors when the plugin attempts to create monitors that should be updated.

I opened a [pr](https://github.com/DataDog/serverless-plugin-datadog/pull/433) to modify the search method to retrieve all monitors instead of only the default 30

## Steps to Reproduce the Problem

  1. Create a serverless application with > 30 monitors
  2. Change the config for one of the monitors
  3. Deploy the change and watch for the 400 syntax error

## Specifications

  - Serverless Framework version: 2.63
  - Datadog Serverless Plugin version: ^5.5.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14
  
## Stacktrace
  
  ```
Serverless: Error occurred when configuring monitors: 400 Bad Request: This could be due to incorrect syntax for find-by-activity-log-id_lambdaErrorRate
  ```

**Comment by sfirrin** [comment]
Hi @johnbuildsthings, thanks a lot for opening this issue and the PR, sorry we missed your PR when you originally opened it. Taking a quick look it looks great, thanks for adding those tests. I'm going to take a closer look later today and will leave a review

**Comment by jcgubbi** [comment]
Hi @johnbuildsthings! Wanted to follow up since I am facing a similar issue. Did upgrading to `v5.49.0` fix this issue for you? I tried upgrading to include your latest PR and are still running into this issue.

**Comment by astuyve** [comment]
Hey folks! We merged the PR mentioned above (https://github.com/DataDog/serverless-plugin-datadog/pull/433) and released it several weeks ago. Feel free to re-open if there are other issues!

Thanks!
