### ISSUE TITLE
Invalid wrapper code when the entrypoint is in a folder called "lambda"

### ISSUE THREAD

**Issue by benweissmann** [DataDog/serverless-plugin-datadog#44]
## Background

I have a python 3.7 project structured like this:

```
serverless.yml
some_module/
  some_file.py
lambda/
  handler.py
```

The `some_module` package contains the actual business logic / reusable code, and the `lambda` folder contains just my lambda handler functions -- so my `serverless.yml` specifies `handler: lambda.handler.some_function`. The `handler.py` function then imports `some_module.some_file` and uses that.

This works fine without `serverless-plugin-datadog`. However, when deployed with `serverless-plugin-datadog`, the plugin wraps the handler to add instrumentation, and generates code like this:

```
from datadog_lambda.wrapper import datadog_lambda_wrapper
from lambda.handler import some_function as some_function_impl
some_function = datadog_lambda_wrapper(some_function_impl)
```

This causes a syntax error because `lambda` can't be used as an identifier.

## Expected Behavior

The plugin should at least warn about this issue and suggest renaming the folder to `lambda_handlers` or something like that.

## Actual Behavior

The plugin quietly deploys invalid code, leading to internal server errors when the lambda function is invoked.

## Specifications

  - Serverless Framework version: 1.67.3
  - Datadog Serverless Plugin version: 0.24.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Python 3.7
  
## Stacktrace
  
  ```
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'datadog_handlers/extract_signature': invalid syntax (extract_signature.py, line 2)
Traceback (most recent call last):
  File "/var/task/datadog_handlers/extract_signature.py" Line 2
    from lambda.handler import extract as extract_impl  
```

**Comment by benweissmann** [comment]
Perhaps the plugin could run [py_compile.compile](https://docs.python.org/3/library/py_compile.html) on the generated code, and error out if the file is invalid?

**Comment by tianchu** [comment]
@benweissmann do you mind upgrading the plugin to its latest version (v1.0.0) and try again? In the latest version, the plugin no longer modify/generate code to wrap your handler, so your issue might have been resolved.

**Comment by jbriones27** [comment]
I am having a similar issue with my project as well except my handlers are kept within a src folder in my project directory.  When deploying using the plugin, I get an unable to import module error - however, when I move the handler function outside of the src folder into the root folder of my project directory this seems to correct the issue.

**Comment by Czechh** [comment]
@benweissmann This is no longer an issue in the current version. I was able to create a similar setup with no issues. The only gotcha is actually naming the handler with `.` instead of `/` in order for the python modules redirect to work.

I'll be adding a patch to handle `/` in handlers.
