### ISSUE TITLE
DD Log not forwarded due to invalid API key

### ISSUE THREAD

**Issue by kvin5529** [DataDog/serverless-plugin-datadog#446]
## Expected Behavior

DD Logs needs to be forwarded when plugin added and properly configured with custom attributes in `serverless.yml` file

```
custom:
  datadog:
    addExtension: true
    injectLogContext: true
    flushMetricsToLogs: true
    enableTags: true
    logLevel: info
    apiKey: ${file(./serverless.env.yml):${opt:stage}.DATADOG_API_KEY}
```

```
plugins:
  - serverless-plugin-datadog
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-lambda-insights
  - serverless-plugin-aws-alerts
```

## Actual Behavior

But DD Logs are not forwarded but ends up with below warnings

```
2023-11-14T00:31:22.986+05:30 | 2023-11-13 19:01:22 UTC | DD_EXTENSION | INFO | retrying the first update of remote-config state (could not acquire agent auth token: unable to read authentication token file: open auth_token: no such file or directory)
-- | --
  | 2023-11-14T00:31:23.050+05:30 | EXTENSION Name: cloudwatch_lambda_agent State: Ready Events: [INVOKE, SHUTDOWN]
  | 2023-11-14T00:31:23.050+05:30 | EXTENSION Name: datadog-agent State: Ready Events: [INVOKE, SHUTDOWN]
  | 2023-11-14T00:31:23.052+05:30 | START RequestId: c81e2b0d-b083-4807-a601-2b5e9b68fd8b Version: $LATEST
  | 2023-11-14T00:31:23.267+05:30 | 2023-11-13 19:01:23 UTC | DD_EXTENSION | INFO | Triggering a flush in the logs-agent
  | 2023-11-14T00:31:23.366+05:30 | 2023-11-13 19:01:23 UTC | DD_EXTENSION | INFO | Successfully posted payload to "https://7-47-1-app.agent.datadoghq.com/api/v1/series", the agent will only log transaction success every 500 transactions
  | 2023-11-14T00:31:23.387+05:30 | END RequestId: c81e2b0d-b083-4807-a601-2b5e9b68fd8b
  | 2023-11-14T00:31:23.387+05:30 | REPORT RequestId: c81e2b0d-b083-4807-a601-2b5e9b68fd8b Duration: 335.56 ms Billed Duration: 336 ms Memory Size: 1024 MB Max Memory Used: 248 MB Init Duration: 3628.51 ms
  | 2023-11-14T00:31:23.602+05:30 | START RequestId: c70ebdc9-f31e-450e-9508-863a4ed79b9f Version: $LATEST
  | 2023-11-14T00:31:23.784+05:30 | 2023-11-13 19:01:23 UTC | DD_EXTENSION | WARN | failed to post http payload. code=403 host=http-intake.logs.datadoghq.com response={"errors":[{"status":"403","title":"Forbidden","detail":"Api key is either forbidden or blacklisted"}]}
  | 2023-11-14T00:31:23.784+05:30 | 2023-11-13 19:01:23 UTC | DD_EXTENSION | WARN | Could not send payload: client error
```
## Specifications

  - Serverless Framework version: 3
  - Datadog Serverless Plugin version: 5.25.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 16

**Comment by kvin5529** [comment]
@astuyve yes, it's valid and I'm not sure how can I configure it for the file read ? Is there any configuration I need to put in `serverless.yml` file ? I feel like file read could be the possible issue here.

```
2023-11-14T00:31:22.986+05:30 | 2023-11-13 19:01:22 UTC | DD_EXTENSION | INFO | retrying the first update of remote-config state (could not acquire agent auth token: unable to read authentication token file: open auth_token: no such file or directory)
```

**Comment by astuyve** [comment]
Thanks! That's a warning from remote config which isn't relevant for this specific issue.

If the API key is resolved correctly by the Serverless Framework and injected as an environment variable as expected, I'd verify that it's copied correctly from the Datadog application and that it's for the correct datacenter (API keys are only valid for the same datacenter they are issued).

If you're not using `us1`/`app.datadoghq.com`, you'll need to set the `site` parameter, which becomes the `DD_SITE` env variable.

Let me know if this helps,
thanks!

**Comment by kvin5529** [comment]
Hi @astuyve thank you for the reply...site is set automatically as `datadoghq.com` in `DD_SITE` env variable. And the app I'm using is `https://app.datadoghq.com`. 

Is there anything else that you can think of that could cause this issue ?

**Comment by astuyve** [comment]
Because this issue handles API keys, you should open a support ticket privately instead of handling this further in a public repo. You can email support@datadoghq.com to open a ticket.

From there we should be able to have someone investigate why the API key is invalid.

Thanks!

**Comment by kvin5529** [comment]
sure, thanks a lot @astuyve

**Comment by astuyve** [comment]
closing as this has been handled via support
