### ISSUE TITLE
id.toArray is not a function after triggering flush and before posting payload to DataDog

### ISSUE THREAD

**Issue by junioramilson** [DataDog/serverless-plugin-datadog#454]
## Expected Behavior
It should not throw any kind of error.

## Actual Behavior
It is throwing an uncaught exception after triggering flush and before posting payload to Datadog agent.

<img width="869" alt="image" src="https://github.com/DataDog/serverless-plugin-datadog/assets/8687422/015bd1c1-89ac-4344-ba94-641d2061aa37">

## Steps to Reproduce the Problem

  I don't know yet.

## Specifications

  - Serverless Framework version: 3.38.0
  - Datadog Serverless Plugin version: 5.54.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 20
  
## Stacktrace
  
  ```
  ERROR	Uncaught Exception 	{"errorType":"TypeError","errorMessage":"id.toArray is not a function","stack":["TypeError: id.toArray is not a function","    at AgentEncoder._encodeId (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/encode/0.4.js:168:13)","    at AgentEncoder._encode (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/encode/0.4.js:96:12)","    at AgentEncoder.encode (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/encode/0.4.js:45:10)","    at Writer._encode (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/exporters/common/writer.js:39:19)","    at Writer.append (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/exporters/common/writer.js:35:10)","    at AgentExporter.export (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/index.js:45:18)","    at SpanProcessor.process (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/span_processor.js:50:30)","    at DatadogSpan.finish (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:183:21)","    at HttpClientPlugin.finish (/opt/nodejs/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js:98:10)","    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/plugins/tracing.js:73:22"]}
  ```

**Comment by joeyzhao2018** [comment]
Hi @junioramilson , thank you for raising this issue. I'm actively working on this now. I'm going to close this ticket and track it here https://github.com/DataDog/datadog-lambda-js/issues/444 in order to sort out the information better. 
Do you mind provide information there on what the upstream service that invokes the lambda is? Thank you very much.

**Comment by junioramilson** [comment]
> Hi @junioramilson , thank you for raising this issue. I'm actively working on this now. I'm going to close this ticket and track it here [DataDog/datadog-lambda-js#444](https://github.com/DataDog/datadog-lambda-js/issues/444) in order to sort out the information better. Do you mind provide information there on what the upstream service that invokes the lambda is? Thank you very much.

Hi @joeyzhao2018, the upstream service is SQS
