### ISSUE TITLE
Plugin does not work when packaging individual python ƛ

### ISSUE THREAD

**Issue by cscetbon** [DataDog/serverless-plugin-datadog#46]
## Expected Behavior
Datadog handler should be added to lambdas when packaging individual functions in Serverless.

## Actual Behavior

The plugin adds the handler to the first archive that is created but not the final one used to actually deploy to aws. It happens when we use that option in Serverless.yaml:
```
package:
  individually: true
``` 

The plugin probably needs to add more hooks when lambdas are packaged individually.

## Steps to Reproduce the Problem

  1. clone branch https://github.com/cscetbon/sls-dd-missing-folder/tree/dd 
  2. run `sls package`
  3. check content of archive .serverless/f1.zip
```
unzip -l .serverless/f1.zip
Archive:  .serverless/f1.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      148  01-01-1980 00:00   datadog_handlers/f1.py
      116  01-01-1980 00:00   f1/handler.py
---------                     -------
      264                     2 files
```
  4. check content of archive .serverless/f1-sls-dd-missing-folder-dev-f1.zip
```
unzip -l .serverless/f1-sls-dd-missing-folder-dev-f1.zip 
Archive:  .serverless/f1-sls-dd-missing-folder-dev-f1.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      116  01-01-2098 00:00   handler.py
---------                     -------
      116                     1 file
``` 

## Specifications
  - Serverless Framework version: 1.70.1
  - Datadog Serverless Plugin version: 0.26.0
  - Lambda function runtime (Python 3.7, Node 10, etc.):  Python 3.7

**Comment by DarcyRaynerDD** [comment]
Hi @cscetbon. Sorry for the delayed response. With v3 of the plugin We migrated to use a new approach. We no longer generate a handler file using the plugin. Instead we've written added a customer handler to the layer/python package. Can you still reproduce this with the latest version of the plugin?

**Comment by cscetbon** [comment]
Unfortunately I'm not working on it atm but maybe you can confirm if it works now with the sample code I provided ? If yes, we can close it

**Comment by Czechh** [comment]
Verified that this issue has been resolved.
