### ISSUE TITLE
Monitors no data

### ISSUE THREAD

**Issue by danielpoonwj** [DataDog/serverless-plugin-datadog#460]
## Expected Behavior

Monitors would be able to reference function metrics automatically.

## Actual Behavior

Monitors such as `timeout` filter metrics like `aws.lambda.timeout` by the tag `aws_cloudformation_stack-id` instead of `aws:cloudformation:stack-id` which is [set automatically by Cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html).

Metrics are automatically tagged with `aws:cloudformation:stack-id` but not `aws_cloudformation_stack-id`. This mismatch causes the monitors to display `NO DATA`.

## Steps to Reproduce the Problem

  1. Configure monitors with defaults as per documentation
```yaml
custom:
  datadog:
    ...
    monitors:
      - timeout:
```
  2. Deploy
  3. Observe created monitor and compare with tags available on the metrics. Monitors reference `aws_cloudformation_stack-id` but only `aws:cloudformation:stack-id` is available as tags on the metrics.

## Specifications

  - Serverless Framework version: 3.30.1
  - Datadog Serverless Plugin version: 5.46.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): `provided.al2` (Go)
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by zARODz11z** [comment]
@danielpoonwj I'm having some issues reproducing the issue, my timeout metrics have the same aws_cloudformation_stack-id as the monitor [tag](https://github.com/DataDog/serverless-plugin-datadog/blob/6661ff5263d8ae1c99fbe9cdf1f089be8706d0d0/src/monitors.ts#L65-L66) 
<img width="1270" alt="Screenshot 2024-03-01 at 12 12 47 PM" src="https://github.com/DataDog/serverless-plugin-datadog/assets/49878080/6bf06242-3735-4b09-a088-5bb0e6ba30b5">

**Comment by astuyve** [comment]
Closing this issue as there's been no reply for several weeks. Please feel free to reach back out if this is still an issue!

Thanks!
