### ISSUE TITLE
Support provided.al2023 runtime

### ISSUE THREAD

**Issue by gpalanivelu** [DataDog/serverless-plugin-datadog#469]
## Expected Behavior
lambda layer gets added to the function that uses provided.al2023 runtime

## Actual Behavior
getting this message 
 Unable to add Lambda Layers to function {function-name} with runtime provided.al2023

## Steps to Reproduce the Problem

deploy a go sample using al2023 (aws recommendation to use that runtime) the extension doesn't get added. 

## Specifications

  - Serverless Framework version:  3.38.0
  - Datadog Serverless Plugin version: 5.57.1
  - Lambda function runtime (Python 3.7, Node 10, etc.): provided.al2023 (Go)

**Comment by zARODz11z** [comment]
Hi @gpalanivelu I was able to reproduce this issue with Amazon Linux 2023. Working on the next steps.

**Comment by zARODz11z** [comment]
https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.59.0 @gpalanivelu

**Comment by gpalanivelu** [comment]
Thanks for a quick fix 🙇
