### ISSUE TITLE
DataDog Serverless Plugin Does Not Allow For Idempotency with Webpack-based Services

### ISSUE THREAD

**Issue by cwardcode** [DataDog/serverless-plugin-datadog#47]
## Expected Behavior
A deployment artifact created with `serverless package` can be deployed using `serverless deploy` to ensure idempotent service deployments. This process worked fine before adding the plugin and its dependencies (`"aws-xray-sdk": "^3.0.1", "datadog-lambda-js": "^2.23.0", "dd-trace": "^0.20.3"`)

## Actual Behavior
After creating a package using `serverless package`,  unzipping the package in a clean directory with only the essential files, and then running `sls deploy` the package fails to deploy with the error shown in the Stacktrace section.

From inspecting the files before and after `sls deploy` is ran: Before running, the files under `datadog_handlers` appear to be compiled by webpack. However, after running deploy, the files appear to be their original plugin-generated versions, trying to reference the other uncompiled source. 

I believe these files get overridden as a result of the serverless plugin-initialization/run phase during deploy, i.e. the first two steps in this output:

```
/tmp -> npx sls deploy --stage test
Serverless: Auto instrumenting functions with Datadog
Serverless: Adding Lambda Layers to functions
Serverless: Bundling with Webpack...
Time: 1300ms
```

## Steps to Reproduce the Problem

  1. In your serverless directory, run `serverless package --stage <stage>`. When finished, a <service>.zip file should be created under the .serverless folder within the same directory you ran `serverless package`.
  2. Copy the <service>.zip folder into a new directory.
  3. Copy over any needed files. In my case, I also needed to copy over `serverless.yml serverless.<stage>.yml source-map-install.js tsconfig.json webpack.config.js`
  3. Run `serverless deploy --stage <stage>`

## Specifications

  - Serverless Framework version: `1.62.0`
  - Datadog Serverless Plugin version: `0.26.0`
  - Lambda function runtime (Python 3.7, Node 10, etc.): `nodejs10.x`
  
## Stacktrace
  
```
309 | Serverless: Auto instrumenting functions with Datadog
310 | Serverless: Adding Lambda Layers to functions
311 | Serverless: Bundling with Webpack...
312 | Time: 76ms
313 | Built at: 05/15/2020 8:53:01 PM
314 | Asset      Size  Chunks  Chunk Names
315 | datadog_handlers/customAuthorizer.js  4.87 KiB       0  datadog_handlers/customAuthorizer
316 | datadog_handlers/getData.js  4.84 KiB       1  datadog_handlers/getData
317 | Entrypoint datadog_handlers/customAuthorizer = datadog_handlers/customAuthorizer.js
318 | Entrypoint datadog_handlers/getData = datadog_handlers/getData.js
319 | [0] ./source-map-install.js 41 bytes {0} {1} [built]
320 | [1] external "source-map-support" 42 bytes {0} {1} [built]
321 | [2] external "dd-trace" 42 bytes {0} {1} [built]
322 | [3] external "datadog-lambda-js" 42 bytes {0} {1} [built]
323 | [4] multi ./source-map-install.js ./datadog_handlers/customAuthorizer.js 40 bytes {0} [built]
324 | [5] ./datadog_handlers/customAuthorizer.js 263 bytes {0} [built]
325 | [6] multi ./source-map-install.js ./datadog_handlers/getData.js 40 bytes {1} [built]
326 | [7] ./datadog_handlers/getData.js 239 bytes {1} [built]
327 |  
328 | ERROR in ./datadog_handlers/customAuthorizer.js
329 | Module not found: Error: Can't resolve '../src/handlers/api/custom-authorizer/handler' in '/codebuild/output/src864296957/src/datadog_handlers'
330 | @ ./datadog_handlers/customAuthorizer.js 4:0-74 6:34-53
331 | @ multi ./source-map-install.js ./datadog_handlers/customAuthorizer.js
332 |  
333 | ERROR in ./datadog_handlers/getData.js
334 | Module not found: Error: Can't resolve '../src/handlers/api/handler' in '/codebuild/output/src864296957/src/datadog_handlers'
335 | @ ./datadog_handlers/getData.js 4:0-56 6:31-47
336 | @ multi ./source-map-install.js ./datadog_handlers/getData.js
```

**Comment by DarcyRaynerDD** [comment]
@cwardcode , sorry for the delayed response. We recently migrated this plugin to use a new approach with v3 and up. We are no longer generate a handler file using the plugin. Instead we've written added a customer handler to the layer/npm package. Can you still reproduce this with the latest version of the plugin?

**Comment by tianchu** [comment]
@cwardcode I'm going to close this issue assuming the latest version fixed the issue. If that's not the case, feel free to reopen :)
