### ISSUE TITLE
Excluding Unnecessary Library Spans in Lambda

### ISSUE THREAD

**Issue by safaozturk93** [DataDog/serverless-plugin-datadog#474]
## Expected Behavior

I would like to keep only the calls to other AWS Services or API requests

## Actual Behavior

It adds a lot of unnecessary spans related to libraries but they're not helpful at all. Is there a way to exclude those spans? I checked documentation of this plugin, ddtrace and datadog documentation but couldn't find anything useful. One request has 600 spans and it's totally unnecessary.

## Specifications

  - Serverless Framework version: 3.31.0
  - Datadog Serverless Plugin version:  5.34.0
  - Lambda function runtime (Python 3.7, Node 10, etc.):  Python 3.10
  
## Stacktrace
  
![Screenshot 2024-03-15 at 12 03 57](https://github.com/DataDog/serverless-plugin-datadog/assets/15890268/f6488481-407a-4a51-ba68-6a51242864e1)
![Screenshot 2024-03-15 at 12 04 02](https://github.com/DataDog/serverless-plugin-datadog/assets/15890268/88eadf58-b0ad-46c3-a059-8ca359ee0895)

**Comment by astuyve** [comment]
Hi @safaozturk93, thanks for reaching out!
This feature is called [cold start tracing](https://www.datadoghq.com/blog/serverless-cold-start-traces/) and helps users identify which dependencies cause their function to experience slow and painful cold starts. For example you can see from the highlighted span in your screenshot that the `src.api.v1.handlers` file loaded in 1.51s.

If it's too noisy, you can skip any library with `coldStartTraceSkipLibs`, set the minimum traced duration with `coldStartTraceMinDuration`, or turn it off entirely with `enableColdStartTracing`. These tuning options are well documented in this project [readme](https://github.com/DataDog/serverless-plugin-datadog).

Hope this helps!

**Comment by safaozturk93** [comment]
Thank you :)
