### ISSUE TITLE
5.60.0 regression - Remote config is disabled; AppSec will not be able to use it

### ISSUE THREAD

**Issue by Fodoj** [DataDog/serverless-plugin-datadog#477]
After upgrading the plugin to 5.60.0, DataDog started spamming to logs with this message: `Remote config is disabled; AppSec will not be able to use it`. From the release notes it's unclear how to disable these warnings.

**Comment by Fodoj** [comment]
Yep, using the extension, java-agent, nothing really specific on the application side directly. :)

**Comment by astuyve** [comment]
I see - can you confirm what the `DD_LOG_LEVEL` env variable (or `logLevel` config in `serverless.yml`) is set to? This is an [info-level log](https://github.com/DataDog/dd-trace-java/blob/e20dfff5e5373a2a3220121b689e995d4feef9d3/dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java#L233), so I'd be surprised if this log is showing up without something like `INFO` or `DEBUG` level being configured.

Thanks!

**Comment by Fodoj** [comment]
I don't have this variable set at all, and the plugin sets it to `warn` by default.

**Comment by astuyve** [comment]
Thanks so much! I'll pass this on to the java team.

**Comment by astuyve** [comment]
This should be fixed in the next agent release. For now, you can squash these logs by setting `DD_APPSEC_ENABLED=false`.

Thanks @Fodoj!

**Comment by Fodoj** [comment]
Great, thanks! Do you know the ETA for the next agent (and plugin) release?

**Comment by astuyve** [comment]
I don't know for certain but I will update this ticket when this is fully released.

Thanks!

**Comment by Fodoj** [comment]
5.62.0 fixes the problem
