### ISSUE TITLE
[Question] Does the Forwader function needs to be in the same AWS region?

### ISSUE THREAD

**Issue by krvajal** [DataDog/serverless-plugin-datadog#49]
I installed the CloufFormation Stack for the AWS integration that comes with the forwarder function. The stack is in *us-east-1* but my functions are running in eu-west-1. Can the forwarder function subscribe to logs groups in a different region?

**Comment by agocs** [comment]
Hey @krvajal , sorry for the delay. I just tried this in my test AWS account. You _cannot_ subscribe the forwarder to the cloudwatch log group of a lambda that's running in a different region. The easiest thing to do would be to launch a new cloudformation stack in eu-west-1. You can safely remove the old stack if you don't need it any more. 

Changing the region for the new stack:
https://a.cl.ly/9ZujWwZm

Deleting the old stack:
https://a.cl.ly/wbuWeRR1

Let me know if I can answer any followup questions!
