### ISSUE TITLE
Add support for serverless v4

### ISSUE THREAD

**Issue by jboone100** [DataDog/serverless-plugin-datadog#493]
## Expected Behavior
`npm i serverless-plugin-datadog --save-dev` should work when using serverless framework version 4+

## Actual Behavior
npm ERR! Could not resolve dependency:
npm ERR! peer serverless@"3.x || 2.x || 1.x" from serverless-plugin-datadog@5.66.0

## Steps to Reproduce the Problem

  1. Install serverless v4
  1. `npm i serverless-plugin-datadog --save-dev`
 
## Specifications

  - Serverless Framework version:  4.1.5
  - Datadog Serverless Plugin version:  5.66.0
  - Lambda function runtime (Python 3.7, Node 10, etc.):  Node v18.16.0

**Comment by astuyve** [comment]
Hi @jboone100, thanks for reaching out. We haven't seen much organic interest in v4. Presumably this is due to the license change among other factors, so I suspect many folks are moving away from Serverless Framework towards CDK and SST.

But we'll keep this ticket open to await more feedback while we explore loosening the dependency.

**Comment by dave-jumptech** [comment]
I would be surprised if there isn't great demand for V4 - the license change does not affect small companies and larger companies will probably appreciate the enhanced support. TBH I'm more likely to stick with serverless v4 and drop datadog if support for v4 doesn't arrive soon

**Comment by astuyve** [comment]
Okay folks, I tried a simple deployment and saw that things seemed to continue working as expected, so I've opened the restriction up in [v5.69.0](https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.69.0).

Please let me know if there are any questions.
