### ISSUE TITLE
Variables are not Replaced in Recommended Monitor Title

### ISSUE THREAD

**Issue by ceagan** [DataDog/serverless-plugin-datadog#495]
## Expected Behavior
When specifying a simple DataDog configuration like the following, the `high_error_rate` monitor should be created with a name that includes the information specific to the deployment and should not include unresolved variable references.

```yaml
custom:
  datadog:
    monitors:
      - high_error_rate:
```

## Actual Behavior
The `high_error_rate` monitor is created with a name of `High Error Rate on $functionName in $regionName for $awsAccount` with the variables left in variable notation.

## Steps to Reproduce the Problem

  1. Create a serverless.yml config as shown above and a DataDog account with no monitors (so that a create is performed rather than an update).
  1. Run `serverless deploy`

## Specifications

  - Serverless Framework version: 3.39.0
  - Datadog Serverless Plugin version: 5.66.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs18.x

**Comment by TalUsvyatsky** [comment]
Hey @ceagan, thanks for creating this issue. This default monitor alerts on any `functionname`, `region`, and `aws_account` in a given stack. The monitor title is expected to have unresolved variable names until alert time, at which point the variables will be populated in the alert notification based on the specific `functionname`, `region`, `aws_account` combo that is experiencing high errors. That said, I think the variables are currently in the wrong format (`$functionName` vs. `{{ functionname.name }}`), so I've gone ahead and filed a ticket on our side.

**Comment by lym953** [comment]
Hi @ceagan, https://github.com/DataDog/serverless-plugin-datadog/pull/499 should have fixed this issue. Please refer to the `Testing Guidelines` section for the current behavior. Thanks!
