### ISSUE TITLE
Vulnerability due to transitive dependency fast-xml-parser

### ISSUE THREAD

**Issue by jkburges** [DataDog/serverless-plugin-datadog#509]
## Expected Behavior

No vulnerability.

## Actual Behavior

Vulnerability as described by https://github.com/advisories/GHSA-mpg4-rc92-vx8v.

## Steps to Reproduce the Problem

  1. npx --yes improved-yarn-audit # in a project which uses this library

## Specifications

  - Serverless Framework version: 4.1.18
  - Datadog Serverless Plugin version: 5.67.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 20

**Comment by astuyve** [comment]
Thanks @jkburges, will fix in the next release

**Comment by jkburges** [comment]
Thank you 🙏

**Comment by jkburges** [comment]
Unfortunately this library still pulls in an older version of fast-xml-parser via https://github.com/DataDog/serverless-plugin-datadog/blob/main/package.json#L60C6-L60C25 😿
