### ISSUE TITLE
Datadog-Node20-x:113 not authorized lambda:GetLayerVersion action  

### ISSUE THREAD

**Issue by Copper-Roc** [DataDog/serverless-plugin-datadog#527]
## Expected Behavior
Be able to deploy lambda functions

## Actual Behavior
```
CREATE_FAILED: GetManifestsLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "User: arn:aws:sts::999999999999:assumed-role/AWSReservedSSO_Administrator_fa663426d9b8de32/h.s@c.com is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-west-2:464622532012:layer:Datadog-Node20-x:113 because no resource-based policy allows the lambda:GetLayerVersion action (Service: Lambda, Status Code: 403, Request ID: a956892d-dd71-4a51-8d4c-85e5d4ac13bf)" (RequestToken: 7a14645e-9989-8ec6-657d-a685d2cded2a, HandlerErrorCode: AccessDenied)
```

This looks to be the same issue as reported in https://github.com/DataDog/serverless-plugin-datadog/issues/65

## Steps to Reproduce the Problem

  1. Use latest version of Datadog Serverless Plugin
  1. Deploy to us-west-2

## Specifications

  - Serverless Framework version: 3.39.0
  - Datadog Serverless Plugin version: 5.70.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node20

**Comment by astuyve** [comment]
Hi @Copper-Roc - thanks for the note.
If you've verified that your own personal access credentials can access this layer, then you've confirmed that this layer is available publicly and should work for you. There's nothing more I can do on our end.

This means there's certainly something actively preventing the layer from being pulled in your IAM permissions used to deploy your function. I would try repeating the test using the exact credentials used by `User:arn:aws:sts::999999999999:assumed-role/AWSReservedSSO_Administrator_fa663426d9b8de32/h.s@c.com`

Unfortunately I'm not sure what else to recommend, you could try adding explicit permissions to allow that SSO user to call `lambda:GetLayerVersion`, or perhaps running an IAM policy simulator or looking at the logs in cloudtrail.

If you have further questions you can open a support ticket, but I do expect that they'd ask you to try what I've already asked here. I wish I could be more helpful.
Thanks!
AJ
