### ISSUE TITLE
No trace sampling option available

### ISSUE THREAD

**Issue by christophasam** [DataDog/serverless-plugin-datadog#544]
## Expected Behavior
DD_TRACE_SAMPLE_RATE or corresponding serverless configuration is available / supported and the sampling rate can be adjusted.

## Actual Behavior
DD_TRACE_SAMPLE_RATE is not taken in consideration, even if it's set

## Steps to Reproduce the Problem

  1. add an env variable DD_TRACE_SAMPLE_RATE = 0.01 to your serverless config and deploy it
  2. check Datadog if the traces are sampled

## Specifications

  - Serverless Framework version: 3.39
  - Datadog Serverless Plugin version: 5.4
  - Lambda function runtime (Python 3.7, Node 10, etc.): 16.15.1

**Comment by purple4reina** [comment]
Hi @christophasam, v5.4.0 of the plugin is over two years old. Would you mind updating to the latest version v5.72.0 and trying again? Let me know if that works, because this feature should definitely be implemented already.

**Comment by purple4reina** [comment]
Ah, nevermind, I found your problem.

![Image](https://github.com/user-attachments/assets/7be1b262-f0d8-49d6-84a1-8d493de93491)

> Note: The use of DD_TRACE_SAMPLE_RATE is deprecated. Use DD_TRACE_SAMPLING_RULES instead. For instance, if you already set DD_TRACE_SAMPLE_RATE to 0.1, set DD_TRACE_SAMPLING_RULES to [{"sample_rate":0.1}] instead.
