### ISSUE TITLE
FR: Add Authoriser Trace under AWS API Gateway Trace.

### ISSUE THREAD

**Issue by ranayash45** [DataDog/serverless-plugin-datadog#546]
## Expected Behaviour
Go Lang Based Custom Authorizer should link trace with Api-Gateway.

## Actual Behavior
In current scenario, Trace of authorizer shown separately over data-dog.

## Similar Issue:
Link: https://github.com/DataDog/serverless-plugin-datadog/issues/252

## Steps to Reproduce the Problem

  1. Create Go Lang Custom Authorizer.
  1. Attach to API Gateway, Enable DD Integration of API-Gateway.
  1. Check Service APM of API-Gateway and verify whether trace is linked or not.

## Specifications

  - Serverless Framework version: aws-lambda-go v1.47.0, datadog-lambda-go v1.18.0
  - Datadog Serverless Plugin version: Using Lambda Extension version 58.
  - Lambda function runtime (Python 3.7, Node 10, etc.):  Go Lang, Rust(Planned for future)
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by purple4reina** [comment]
Thanks @ranayash45, I've created the ticket in our system to track your feature request.

**Comment by ranayash45** [comment]
How can I track the progress ??? @purple4reina

**Comment by ranayash45** [comment]
What's the status of this feature?

**Comment by ranayash45** [comment]
Hello @purple4reina, can you please tell the status of created ticket???

**Comment by ranayash45** [comment]
Can you please share update over this?
