### ISSUE TITLE
`exclude´ still injects a function handler property, does not work with the new `image` property

### ISSUE THREAD

**Issue by hawkaa** [DataDog/serverless-plugin-datadog#88]
Hi there.

I am developing a service where one of our lambdas will be running using a custom ECR image as per [AWS's announcement on container image support](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/). The serverless framework supports this in the new 2.15 version and you can now specify `image` instead of `handler` per function. If you supply both, it fails, which is expected and wanted behavior.

However, the `serverless-plugin-datadog` injects a custom handler which makes serverless to fail the validation check before deploying.

I tried to include my function in `custom.datadog.exclude` but it seems to still inject the handler. I had to make a `foo` runtime which this plugin does not understand to mitigate the problem.

## Expected Behavior

a) exclude does not inject a handler to the function
b) this plugin does not try to inject handlers to functions specified with `image` and optionally gives a warning

## Actual Behavior

Serverless deployment fails with `Either "handler" or "image" property (not both) needs to be set on function "convert-docker".`

## Steps to Reproduce the Problem

  1. add `serverless-plugin-datadog` to your project
  2. add a new function `foo` with an `image` attribute
  3. add `foo` to `custom.datadog.exclude`

## Specifications

  - Serverless Framework version: 2.15.0
  - Datadog Serverless Plugin version: 2.9.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): n/a
  
Let me know what you think! Future plans and discussions for helping users with datadog integrations in docker containers in AWS lambda would also be really interesting.

**Comment by DarcyRaynerDD** [comment]
Hi @hawkaa, I've just released v2.10.0 of the plugin, which includes the new 'exclude' feature. Could you try that again as a workaround until we have more support for the new 'image' option.

**Comment by hawkaa** [comment]
Seems to work, but I am getting another error with v2.10.0 that seems unrelated to this fix:

```
ServerlessError: An error occurred: ConvertDashdockerLambdaFunction - Value of property Variables must be an object with String (or simple type) properties.
      at /Users/hakon/code/ifc2obj/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:99:23
      at processImmediate (node:internal/timers:462:21)
  From previous event:
      at /Users/hakon/code/ifc2obj/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:27:12
```

I will investigate and open a new issue if it's not on my end.

**Comment by hawkaa** [comment]
@DarcyRaynerDD It is an issue with the exclude functionality. It writes a list to the environment variables which Cloudformation does not handle.

This happens both for the dockerized lambda and the original lambda. Here's an example for the ordinary lambda:

```json
    "ConvertLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "code-upload",
          "S3Key": "serverless/ifc2obj/prod/1608191675674-2020-12-17T07:54:35.674Z/ifc2obj.zip"
        },
        "Handler": "datadog_lambda.handler.handler",
        "Runtime": "python3.7",
        "FunctionName": "ifc2obj-prod-convert",
        "MemorySize": 10240,
        "Timeout": 300,
        "Tags": [
          {
            "Key": "dd_sls_plugin",
            "Value": "v2.10.0"
          },
          {
            "Key": "service",
            "Value": "ifc2obj"
          },
          {
            "Key": "env",
            "Value": "prod"
          }
        ],
        "Environment": {
          "Variables": {
            "NODE_ENV": "production",
            "S3_BUCKET": "import-manager-storage",
            "SENTRY_DNS": "https://438fb83e917b4d4b88db789da33b31c3@sentry.io/2959128",
            "DD_SITE": "datadoghq.com",
            "DD_LOG_LEVEL": "info",
            "DD_FLUSH_TO_LOG": true,
            "DD_TRACE_ENABLED": true,
            "DD_LOGS_INJECTION": true,
            "DD_EXCLUDED_FUNCTIONS": [
              "convert-docker"
            ],
            "DD_MERGE_XRAY_TRACES": false,
            "PATH": "$PATH:/opt/ifcopenshell/bin",
            "DD_LAMBDA_HANDLER": "handler.handler"
          }
        },
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Layers": [
          {
            "Ref": "IfcopenshellLambdaLayer"
          },
          "arn:aws:lambda:eu-west-1:464622532012:layer:Datadog-Python37:26"
        ]
      },
      "DependsOn": [
        "ConvertLogGroup"
      ]
    },
```

**Comment by tianchu** [comment]
@hawkaa thanks for your contribution! I'm going to close this issue as your [PR](https://github.com/DataDog/serverless-plugin-datadog/pull/91) has already been released.

We are planning on some general improvements to the plugin for functions deployed using a container image.
