### ISSUE TITLE
Request: Support log groups with an existing subscription

### ISSUE THREAD

**Issue by BryceKK** [DataDog/serverless-plugin-datadog#95]
## Expected Behavior
That log groups with only one unknown subscription would still allow a subscription to the datadog forwarder to be created

Somewhat recently, cloudwatch was updated to allow two parallel subscriptions on a log group: https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-cloudwatch-logs-now-supports-two-subscription-filters-per-log-group/. This should make it OK for the plugin to find only one unknown subscription and still create a subscription for the datadog forwarder

## Actual Behavior
If the log group has any unknown subscription at all, the plugin will not create one.

## Steps to Reproduce the Behaviour

1. Create a lambda function and deploy it with a log group subscription to something other than the datadog forwarder
2. Add the datadog serverless plugin to the serverless.yml and configure it to forward logs to an existing datadog forwarder lambda
3. You will get a message when deploying saying `Subscription already exists for log group [insert log group name]. Skipping subscribing Datadog forwarder` and the datadog forwarder subscription will not be created

It seems right to me that this would be supported now, would be curious to hear if there are any concerns or reservations around this. Happy to make a PR if it's not a problem to just change the requirements for creating a subscription from "As long as the log group doesn't have an unknown subscription" to "As long as the log group doesn't have 2 unknown subscriptions"

**Comment by DarcyRaynerDD** [comment]
Hi @BryceKK, thanks for the detailed feature request. This is on our radar, and we're actually working on supporting this soon. We'll post a message here when we have an update.

**Comment by zARODz11z** [comment]
Hi **@BryceKK**, the Serverless plugin now has support for two subscription filters per CloudWatch log group in version 2.13.1.
